### ISSUE TITLE
Support dumping out config file from UI and command line

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#116]
Add an `mb save` action to the command line, and a button in the UI, that dumps a
configfile.
- `mb save` saves the result of GET /imposters?replayable=true to mb.json in the current directory
- `mb save --configfile config.json` saves the result of GET /imposters?replayable=true to config.json
- `mb save --removeProxies` saves the result of GET /imposters?replayable=true&removeProxies=true to mb.json

**Comment by shubhekshajalan** [comment]
Hey, I'd like to work on this. Can you guide me how to get started?

**Comment by bbyars** [comment]
Hi there,
The changes will take place in here: https://github.com/bbyars/mountebank/blob/master/bin/mb

There's a switch at the bottom that you'll add a case statement to for the save, and you'll need to add the --removeProxies flag to the booleanOptions variable.  The putConfig function already shows an example of making an HTTP call.

**Comment by bbyars** [comment]
closed as of 918d14c. Will revisit UI if it's requested.
