### ISSUE TITLE
Add CSS linting to the build

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#117]
See https://www.npmjs.com/package/grunt-contrib-csslint

**Comment by shubhekshajalan** [comment]
Hey, can you elaborate a little on this task? I'm a beginner and I'd like to take this up.

**Comment by bbyars** [comment]
Sure.  I usually just do "npm install grunt-contrib-csslint --save-dev" and that adds the version specifier to package.json automatically (that way I don't have to remember what those strange glyphs in front do - the carets and tildes, etc ;>).

You're correct about the stylesheets directory, although there's a vendor stylesheet in there, so you'll need to exclude the jqueryui sheet (according to the grunt docs at http://gruntjs.com/configuring-tasks#globbing-patterns, the ! prefix can exclude a file).

As far as options, I'm mostly interested in just getting _something_ in place, even if it only detects errors.  This page describes the rules (https://github.com/CSSLint/csslint/wiki/Rules), and I assume the "Possible Errors" rules makes a decent starting point, although in general I'm OK with any set of rules that improves the maintainability and doesn't require completely rewriting all the CSS that's already there.

The usage examples (https://www.npmjs.com/package/grunt-contrib-csslint#usage-examples) appear to show configuration for different tasks, e.g. one for "grunt csslint:strict" and one for "grunt csslint:lax".  The mountebank code shouldn't need that: a single top-level options is fine, with all vendor CSS excluded (jqueryui).  I haven't played enough with csslint to know what all it does, so I'm not fussy about the formatter or anything.  Feel free to play with it and see what you think looks good.

Thanks for reaching out.  Hope that helps, but feel free to let me know if you need more information.
-Brandon

**Comment by shubhekshajalan** [comment]
I've a few more doubts. 
1) "npm install grunt-contrib-csslint --save-dev" will be done externally while installing? So I don't need to specify a version for this package like it's in place for all others? Currently, I added ~0.4.0.

2)  I included all the stylesheets except for jquery-ui.css in the src parameter in the gruntfile. Do I need to specify another another parameter explicitly? For the example in the documentation, they've written two different tasks, which you said isn't needed. So just the basic skeleton needs to be in place for it to work?

**Comment by bbyars** [comment]
Hi there,
1) Adding ~0.4.0 is great.  The command "npm install grunt-contrib-csslint
--save-dev" would have added a version if you hadn't already so it's a good
option when you don't know the latest version.  I periodically update all
dependencies to the latest version so it's not anything to worry about.

2) Yes, I think just the basic skeleton is fine.  Feel free to play around
with it; I'll gratefully accept any contribution :)

-Brandon

**Comment by shubhekshajalan** [comment]
I'm done modifying both the files. The basic skeleton is in place. However, I can't figure out how to test it. I installed the grunt cli and tried to use the command ```grunt csslint```, but that doesn't seem to work. It's doing nothing basically. Not sure what I am doing something wrong.

**Comment by bbyars** [comment]
If I'm reading this right, you'll need to set some rules to a value of 2 to make it error: https://www.npmjs.com/package/grunt-contrib-csslint#options.  That's my preference - have errors break the build instead of warnings that show up in reports no one looks at...

With that, you should be able to change the CSS to violate the rule.  For instance, set the important rule to 2 and add an important specifier to one of the CSS values as shown here: https://github.com/CSSLint/csslint/wiki/Disallow-%21important.  Running grunt csslint should error (return a non-zero exit code - visible as `echo $?` on Mac/Linux and as `echo %errorlevel%` on windows).

**Comment by shubhekshajalan** [comment]
I got everything to work. However, there is a minor glitch which I am not able to figure out.
```
csslint: {
        	strict: {
			    options: {
			      important: 2,
			      ids: 2
			    },
			    src: [
			    'src/**/*.css', 
			    '!src/**/jquery-ui.css'
			    ]
			}
        }
    }); 
```
This is what I added in the gruntfile. However, the behavior is highly dependent on what I name the array in which I'm storing files as. If I name it ```src```, this is the output:
![image](https://cloud.githubusercontent.com/assets/7693422/11496047/826274ec-9835-11e5-8fec-0568f3d0bb31.png)
And if I name it as target/all, this is the output:
![image](https://cloud.githubusercontent.com/assets/7693422/11496103/d48bc8ea-9835-11e5-8e40-ceab5414e8f5.png)

I cannot figure out why it is failing in the first case and why no errors are being displayed in the second case.

**Comment by NickMcG** [comment]
It looks like the 2nd screenshot is linting 0 files, but they are all lint free. I think the 1st screenshot is the way to go; it is catching the correct errors.

**Comment by shubhekshajalan** [comment]
Yes, but it also says that the task failed. From whatever I could gather, this happens when you try to lint vendor stylesheets, but I've explicitly excluded it. So I'm clueless why this happening.
Also, I specifically introduced ```!imporant``` in two stylesheets before linting, so the second screenshot doesn't make too much sense.

**Comment by bbyars** [comment]
No, it's correctly failing because I incorrectly use ids as CSS selectors.
That proves that the linting is doing exactly what it's supposed to, and
it's exposing the fact that I have some CSS to clean up.  Nick is right -
the first screenshot is the way to go.
-Brandon

**Comment by shubhekshajalan** [comment]
I think I might have misinterpreted what is meant by a failing task. I assumed that it means that the csslint task isn't doing its job correctly. 
So, I'll commit these changes and create a pull request?

**Comment by bbyars** [comment]
Yes please, this is a good change.
