### ISSUE TITLE
Stubs documentation?

### ISSUE THREAD

**Issue by mdaley** [bbyars/mountebank#126]
Hi,

On this page about stubs:

http://www.mbtest.org/docs/api/stubs

I was wondering whether the example could be improved?

What confuses me is that, after the imposter has been set up, the first request is to the /imposters resource on port 4545.  Now, I know that works, but wouldn't it be more correct that the request should be to /customers/123?  The same goes for the second request.  

Also, to make a useful stubbing of a remote service for test purposes, I'd want only calls to valid resources to return success responses.  In this case I can make a request to any resource on port 4545, e.g. /anythingatall, and the request will succeed.  Is there a case for describing the use of predicates here so that only valid requests succeed?

**Comment by bbyars** [comment]
You're absolutely right, thanks for catching this. Fixing now.
