### ISSUE TITLE
Support a response executing only N times

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#130]
Per Matt Daley:
The second is that I want specific responses to a request to occur once only; and after that any additional request should result in a 500 response.  Or, sometimes, I want a response to be generated a set number of times.  And I don't want the responses to cycle as they seem to do.  Is there some way of configuring a request/response pair to occur a specific number of times?

**Comment by njenan** [comment]
I'd be interested in implementing this feature. Just taking an initial stab at the interface for this, I am thinking that this would be be implemented with a predicate that counts the number of times an imposter has been invoked.  Something like this:

```javascript
{
  "port": 4545,
  "protocol": "http",
  "stubs": [
    {
      "responses": [{ "is": { "statusCode": 200 } }],
      "predicates": [
        {
          "equals": {
            "path": "/test",
            "invoked": 0
          }
        }
      ]
    },
    {
      "responses": [{ "is": { "statusCode": 500 } }],
      "predicates": [
        {
          "equals": {
            "path": "/test"
          }
        }
      ]
    }
  ]
}
```

So the first request would have an invoked count of 0, and return the first 200 response, subsequent responses would fail to match and fall back to the 500 response.  There could also be different fields such as 'invokedGreaterThan' and 'invokedLessThan' (and possibly 'invokedGreaterThanOrEqual' and 'invokedLessThanOrEqual'?).

The other way I was thinking was that I could introduce additional predicate operators 'lessThan', and 'greaterThan', which would wrap the 'invoked' field:

```javascript
"greaterThan": {
    "invoked": 10
}

"lessThan": {
    "invoked": 5
}
```

A disadvantage to this last approach would be creating a predicate operator exclusively for 'invoked' but would avoid creating special field(s) that need to be applied to the request object.

Any thoughts?

**Comment by nottyo** [comment]
That's a good idea. I'm waiting for this feature. Cheers

**Comment by bbyars** [comment]
Hi there,
Thanks for your interest, and thinking through an interface. I had actually
started this feature (though I'm happy to back out of it) with a separate
interface using behaviors, because it doesn't strike me as a conditional on
the request (which predicates are meant for) so much as a behavior on the
response. The interface I had in mind looked something like this:

responses: [
  {
    is: { body: 'First response' },
    _behaviors: { repeat: 2 }
  },
  {
    is: { body: 'Second response' },
    _behaviors: { repeat: 3 }
  }
]

That also composes well with the other behaviors (wait and decorate), which
is one of my goals for any new behavior.

The biggest trick is to ensure that the state isn't kept in the imposter
JSON (e.g., not to subtract from the repeat field in my example, or add to
the invoked field in yours) so that if people save the imposter JSON
because they want to save some proxy data, they aren't accidentally saving
intermediate state on the repeat.

Let me know if that makes sense, and if you still want to take a stab at
the feature.
-Brandon

**Comment by njenan** [comment]
That makes sense, and I think that putting this in behavior makes more sense than a predicate.  I'll take a look at the source code again and take a swing at it.

**Comment by bbyars** [comment]
Perfect - let me know if you need any help. Thanks!
