### ISSUE TITLE
Mountebank tries to parse javascript file saved by proxy using ejs

### ISSUE THREAD

**Issue by carlos-granados** [bbyars/mountebank#131]
I have a js file which is read using the proxyOnce method. Then I call the DELETE method on the imposter using ?removeProxies=true&replayable=true to get a replayable imposter file. If i then try to upload this file to Mountebank it complains about "Could not find matching close tag for "<%"". This is because it is trying to parse the content of this js file as though it was a ejs template. Any files that are created with ?removeProxies=true&replayable=true do not need to be parsed by ejs because all the templates would have already been rendered before producing this output. So I think we need a new command line switch ("--no-parse" ?) that removes ejs parsing

**Comment by bbyars** [comment]
Fixed as of 03d9d4f
