### ISSUE TITLE
PATH output not wrapped around for /config

### ISSUE THREAD

**Issue by dotIN** [bbyars/mountebank#133]
When a request is sent to http://localhost:2525/config
The output in Environment table for PATH variable is no wrapped looks/feels odd.
mb version	1.4.3
Platform/OS : Please check the screenshot

![mbtest](https://cloud.githubusercontent.com/assets/164935/13970322/e0ba9c3a-f0ec-11e5-9d34-ac00afc71699.PNG)

**Comment by bbyars** [comment]
Thanks for reporting the issue. In the end I decided to remove the environment variables from the screen altogether as I'm concerned about leaking sensitive information (e.g. passwords) from machines running mountebank. For instance, if a continuous integration agent is running mountebank, developers could pull up this page to see credentials to write to artifact repositories, etc.
