### ISSUE TITLE
unable to call HTTPS server using the proxyOnce setup in imposter.

### ISSUE THREAD

**Issue by agnibrata86** [bbyars/mountebank#136]
imposter Json as below:
{
 "port": 4545,
 "protocol": "http",
 "name": "FirstRESTimposter",
 "stubs": [
    {
     "responses": [  
        {
         "proxy": {
           "to": "https://serverIP:port",
           "mode": "proxyOnce",
            "key": "-----BEGIN RSA PRIVATE KEY-----\n pem rsa key values \n-----END RSA PRIVATE KEY-----",
            "cert": "-----BEGIN CERTIFICATE-----\n pem cert values \n-----END CERTIFICATE-----",
            "predicateGenerators": [
              {
                "matches": {
                  "method": true,
                  "path": true
                }
              }
            ]
          }
        }
      ]
     }
    ],  
 "_links": {
    "self": {
      "href": "http://localhost:2525/imposters/4545"
    }
  }
}

Req Sent from SOAP UI:

GET http://localhost:4545/appname/integration/path1/path2/path3/path4/data HTTP/1.1
Accept-Encoding: gzip,deflate
Api-Key: keyValue
Host: localhost:4545
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

Error:

{"errors": [{
   "code": "EPROTO",
   "errno": "EPROTO",
   "syscall": "write",
   "message": "write EPROTO",
   "name": "Error",
   "stack": "Error: write EPROTO\n    at Object.exports._errnoException (util.js:856:11)\n    at exports._exceptionWithHostPort (util.js:879:20)\n    at WriteWrap.afterWrite (net.js:763:14)"
}]}

**Comment by bbyars** [comment]
appears to be related to this: https://github.com/nodejs/node/issues/3692

**Comment by agnibrata** [comment]
able to make it work.

**Comment by bbyars** [comment]
Allowing overriding the cipher.
