### ISSUE TITLE
SSL/TLS is not supported with TCP imposter

### ISSUE THREAD

**Issue by leemeador** [bbyars/mountebank#149]
You can tell MB that you want to use encrypted HTTP (i.e. HTTPS). 
You can't tell MB that you want your TCP traffic to be encrypted. 

I would suggest a new protocol, TLS. It would work very much like the TCP protocol but add options similar to those HTTPS has to provide one directional authentication or bi-directional, certs and so forth.

**Comment by bbyars** [comment]
Good idea, thanks for the suggestion.

And good to hear from you :)

**Comment by nav** [comment]
@bbyars This is closed as completed. Is TLS actually supported for TCP imposters? or is it just missing documentation?
