### ISSUE TITLE
Update Version on NPM to 1.6

### ISSUE THREAD

**Issue by Tzinov15** [bbyars/mountebank#156]
The 1.6 version that is on github contains the <a href="https://github.com/bbyars/mountebank/commit/d8f16850eecd217697de27bcd164c5b962bf82d2#diff-bfeda5cd73eaa6ae3ecf035dbe2d5c3b">fix</a> for the broken API when using Node 6.2 while the version on NPM (1.5.1-beta.1115) does not. It would be great to have this fix on NPM since right now a project of mine that relies on Mountebank must use the Github repo as a dependency as opposed to the NPM module. Thanks!

**Comment by RookY2K** [comment]
Version 1.6 is now on NPM.

**Comment by mattherman** [comment]
@bbyars Should this be closed now based on the previous comment from @RookY2K ?

**Comment by bbyars** [comment]
Yes it should, thanks for the prompt.
