### ISSUE TITLE
The /imposters/{port} page always displays the port as 2525

### ISSUE THREAD

**Issue by mattherman** [bbyars/mountebank#160]
When viewing the details of an imposter on the /imposters/{port} page it will always display port 2525 instead of the port the imposter was created on.

For example, say you create an HTTP imposter on port 3000. The header on the imposter details page will say "http Imposter on port 2525" instead of "http Imposter on port 3000".

**Comment by mattherman** [comment]
I attempted to resolve this myself, but I got a little lost.

I first looked at imposter.ejs and saw that it is simply displaying the port property of the imposter object that is retrieved:

`<h1><%= protocol %> Imposter on port <%= port %></h1>`

Following that to imposterController.js where it calls .toJSON on the imposter which sets the port property to server.port on line 87:

`var result = {
                    protocol: Protocol.name,
                    port: server.port
                };
`

That server.port property seems like it should be set in the create function that takes in the options defined on line 38 of abstractServer.js. If I am understanding the promises correctly, it seems like the deferred.resolve in server.listen is where the port property is actually set on the server.

Am I on the right track? And if so, I'm confused how it is getting 2525 back instead of the real port number.

**Comment by bbyars** [comment]
Thanks for taking a look at this. You're looking at the right code. It
looks like there's a variable collision with a global variable set in
mountebank.js (line 87), to define the port of the running site itself
(used in all the examples in documentation). Definitely confusing - I think
we need to either rename the global or pass in a container object to
imposter.ejs

**Comment by mattherman** [comment]
I'm interested in what you mean by "pass in a container object to imposter.ejs", but I'm not sure I understand what you mean? At a high-level what would this look like?

**Comment by bbyars** [comment]
I mean simply adding a layer of indirection. Right now the imposter object
gets passed, so it looks something like this:

{
  protocol: "http",
  port: 3000,
  stubs: [...]
}

and the "port" variable is colliding with the global port. A relatively
straightforward fix would simply be to pass in an extra container from the
controller to imposter.ejs, something like:

{
  imposter: {
    protocol: "http",
    port: 3000,
    stubs: [...]
  }
}

and change imposter.ejs to use "imposter.port" instead of "port", avoiding
the collision.

-Brandon

**Comment by bbyars** [comment]
Fixed as of c0d6990
