### ISSUE TITLE
HTTPS proxying without client certificate and key.

### ISSUE THREAD

**Issue by nottyo** [bbyars/mountebank#161]
I want to configure Mountebank as proxyAlways mode sending my requests to the actual HTTPS servers without client certificate or key like when I executed command `curl -k https://myserver.test.com`
#### Expected behaviour

Proxy mode can forward requests without any client certificate, key like _curl -k_ command
...
#### Actual behaviour

I got an error

```
"errors": [
    {
      "code": "invalid proxy",
      "message": "Unable to connect to \"https://myserver.test.com\"",
      "name": "Error",
      "stack": "Error\n    at Object.from (/usr/local/lib/node_modules/mountebank/src/util/inherit.js:15:17)\n    at Object.InvalidProxyError (/usr/local/lib/node_modules/mountebank/src/util/errors.js:13:30)\n    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/mountebank/src/models/http/httpProxy.js:163:40)\n    at ClientRequest.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)\n    at TLSSocket.socketErrorListener (_http_client.js:256:9)\n    at emitOne (events.js:77:13)\n    at TLSSocket.emit (events.js:169:7)\n    at emitErrorNT (net.js:1253:8)"
    }
]
```

...
#### Steps to reproduce

I've configured Mountebank like this

```
"responses": [
     {
         "proxy": {
         "to": "https://myserver.test.com",
         "mode": "proxyAlways"
      }
    }
]
```

Noted that _myserver.test.com_ is configured with HTTPS SSL with self-signed certificate (actually, it's a load balancer HTTPS configuration)
...
#### Software versions used

```
OS         : OSX
mountebank : 1.5.1-beta.1115
node.js    :
  (only if installed via npm)
Installation method : tar.gz
  (npm, zip, tar, pkg, deb, rpm)
```
#### Log contents in mb.log when running mb --loglevel debug

```
I've shown it in actual behaviour
```

**Comment by bbyars** [comment]
Thanks for submitting. Unfortunately, I haven't been able to reproduce the issue. As far as I can tell, mountebank already uses the equivalent of the curl -k switch and does not validate the server certificate with a CA, which makes me wonder if there's something else about https://myserver.test.com that's rejecting the connection. There's even a test for this scenario in the mountebank code base that does exactly this, and I reviewed it to ensure it's testing against a self-signed cert.

Can you reproduce with something I can run locally?

**Comment by nottyo** [comment]
Hi @bbyars 
     I think the root cause is my target HTTPS server has configured self-signed certificate using cipher '**RC4-MD5**' which is quite old cipher for SSL/TLS protocol. I've checked the cipher in my target server using '_openssl_' command

    openssl s_client -connect <ip>:<port>
 
And this is the result

    New, TLSv1/SSLv3, Cipher is RC4-MD5
    Server public key is 2048 bit
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    SSL-Session:
        Protocol  : TLSv1
        Cipher    : RC4-MD5
        Session-ID: <session-id>
        Session-ID-ctx: 
        Master-Key: <master-key>
        Key-Arg   : None
        Start Time: 1479800512
        Timeout   : 300 (sec)
        Verify return code: 18 (self signed certificate)

Then I've written a sample https client on nodejs to connect to my target server. Here is my sample code
**_https_request.js_**

    const https = require('https');
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
    var options = {
      hostname: '<ip>',
      port: 443,
      path: '/path/to/resource',
      method: 'GET',
      //ciphers: 'RC4-MD5'
    };
    var req = https.request(options, (res) => {
    console.log('statusCode', res.statusCode);
    console.log('headers', res.headers);

    res.on('data', (d) => {
        process.stdout.write(d);
    });
    
    });
    req.end();
    req.on('error', (e) => {
        console.error(e);
    });

I run this file on my nodejs and got an error which is the same error from Mountebank.

    bash$node https_request.js 

    { Error: read ECONNRESET
        at exports._errnoException (util.js:1026:11)
        at TLSWrap.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

But if I uncomment the "**cipher**" parameter in my request options, the server will accept my request and return response message back to the client.

    bash$node https_request.js 

    statusCode 200
    headers { server: 'Apache-Coyote/1.1',
          'x-application-context': 'application:dev:8443',
          'content-type': 'text/plain;charset=ISO-8859-1',
          'content-length': '16',
          date: 'Tue, 22 Nov 2016 07:46:50 GMT',
          connection: 'close' 
     }

That means my target server required clients to send a request with 'cipher' parameter. 
Am I understand its behaviour correctly? 
So can you provide more options for HTTPS request object?

**Comment by bbyars** [comment]
Thank you for the awesome research - I very likely never would have unearthed that scenario without you providing so much detail. I changed the proxy ciphers to ALL, which as I understand it, includes the older insecure ciphers. If you get a chance, can you test it out? The change isn't released yet, so you'll have to use either:

* npm install mountebank-dev
* One of the install downloads available on the pre-release site: http://mountebank-dev.herokuapp.com/docs/install

**Comment by nottyo** [comment]
@bbyars 
I've tested your fixed with my scenario. Unfortunately, it doesn't work. It throws the same error message (_unable to connect to 'https://<ip>'_) I don't know why because the cipher 'ALL' should covered the cipher 'RC4-MD5'. To make it work, I have to set specific cipher to 'RC4-MD5' Could you please allow the user to override your cipher setting? you may set the default one to 'ALL' if no 'ciphers' setting under proxies request.

**Comment by bbyars** [comment]
OK thanks for testing. I'll add a cipher field to override the defaults.

**Comment by bbyars** [comment]
Fixed as of 9b1a388. You can now pass a ciphers field to the proxy.

**Comment by nottyo** [comment]
@bbyars 
I've tested your fixed and it works. Thank you so much.

**Comment by bbyars** [comment]
Perfect - thanks!
