### ISSUE TITLE
Support persistent startup

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#167]
Support starting mountebank in persistent mode, so that the up-to-date imposter configuration is always on the filesystem in case mountebank crashes or the user shuts it down without first running `mb save`

## Interface

Allow starting mountebank with the `--savefile` option used in `mb save`:

``mb --savefile mb.json``

Any imposters created through either the API or added via proxying should be automatically added to the savefile, such that

``mb restart --configfile mb.json``

should recreate the exact same imposters, and

``mb restart --configfile mb.json --removeProxies``

should start without the proxies.

## Acceptance Criteria

The result should include automated tests (in the functionalTest/commandLine directory) that verify the following:

When I run `mb --configfile test.json --savefile mb.json`
Then mb.json contains the evaluated content of test.json (equivalent to GET /imposters?replayable=true)

Given I run `mb --savefile mb.json`
When I POST /imposters, PUT /imposters, DELETE /imposters, or DELETE /imposters/{id}
Then mb.json should contain the equivalent of GET /imposters?replayable=true

Given I run `mb --savefile mb.json` and upload a proxy response
WHEN I make a call to the proxy, creating a new saved response
Then mb.json should contain the equivalent of GET /imposters?replayable=true

**Comment by stkac55** [comment]
@bbyars Jay and I have been working through this solution and are very close to implementation.  Let me know if you want to meet to discuss progress and any modifications.

**Comment by bbyars** [comment]
Excellent! I'm a little busy over the next few days. Are y'all available
Wednesday 5/17? I can find a time most slots that day.

**Comment by stkac55** [comment]
Yeah we can make time sometime that morning.  Would 10am EST or 11am EST work for you?

**Comment by bbyars** [comment]
Let's do 11am EST. I'll send an invite.

**Comment by cliffmeyers** [comment]
I see a fair amount of work done toward this in https://github.com/stkac55/mountebank/commit/e2cb94f2d351bfdd0a7fc78019bbd96f7cef13c3  are there any plans to merge this in the near future? It's unclear to me how close to done the work is.

**Comment by bbyars** [comment]
Thanks for the poke. I did spend several hours trying to merge this in the
past but was unable to do so -- both with merge conflicts which I tried to
resolve and broken tests after attempting to force it in. @stkac55 - I
realize you've probably forked this internally at this point. I suggest
killing the PR given the merge problems. Thoughts?
-Brandon

**Comment by stkac55** [comment]
Hey Brandon,  Yes I think that's probably the best course of action to move forward.  I'd be happy to look at resolving some of the conflicts, but I probably won't be able to get to it for awhile.  

I'll close the PR as suggested.

**Comment by cliffmeyers** [comment]
@stkac55 would you be willing to provide a little summary of how you saw this functionality working in your original commit? Our team has needs in this area, and if your approach aligns with our needs, we might be able to implement and contribute it back. Or I might be able to do the work in my spare time. It would just help to be aligned before anyone digs in to do the work.

**Comment by stkac55** [comment]
Sure, no problem.  I'll provide an overview and let Brandon fill in.

**Comment by bbyars** [comment]
Linking first implementation with #279.
