### ISSUE TITLE
Matches predicate incorrectly uses case sensitive compares for object keys

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#169]
Reported here: https://groups.google.com/forum/#!topic/mountebank-discuss/p-n4U-3dBuM

The following predicate does not match if the header is "authorization" instead of "Authorization", even though it should be case-insensitive by default:

```
{
    "matches": {
        "headers": {                                        
            "Authorization": "Bearer [a-zA-Z0-9-_]{1,100}"                                  
        }
    }
```

**Comment by bbyars** [comment]
closed as of 5b96071

**Comment by cabbonizio** [comment]
Many thanks for fixing this.  We have upgraded to 1.7.1 and it fixed out problem.  I work with the developer who reported this on Google groups and we discovered this after finding out our API gateway forces request headers to lower-case when calling downstream services.   Working like a charm very special thanks for addressing this so quickly we really appreciate it and love this software.

**Comment by bbyars** [comment]
Happy to help, glad you guys were able to find the bug.
