### ISSUE TITLE
mb stop or restart should work across terminal sessions

### ISSUE THREAD

**Issue by markhu** [bbyars/mountebank#181]
#### Expected behaviour

`md stop` should work even if typed from a different terminal window

#### Actual behaviour

* `md stop` only worked for me if `md` was running in the background of the current terminal session.
* `md restart` is even worse, erroring out with "throw ... Error: listen EADDRINUSE :::2525"

#### Steps to reproduce

1. in first terminal window, type: `md`
2. in second terminal, type: `md stop`  # nothing happened

#### Software versions used

OS         : Mac OSX "Yosemite" 10.10.5
mountebank : 1.7.2
node.js    : 7.2.1
Installation method : npm

#### Log contents in mb.log when running mb --loglevel debug

(none)

**Comment by bbyars** [comment]
Hi there,
Thanks for reporting. Unfortunately I haven't been able to reproduce, which means it's likely something in your environment. I tried with the same OS, mountebank version, and nodejs version as you. One thing I could think of was if the second terminal session was using a different version of nodejs, but that also worked in my testing.

Can you think of anything else that could be unique in your environment? Lacking that, would you be wiling to jump on a Skype call to demonstrate the problem?

**Comment by bbyars** [comment]
Hi there,
Thanks for reporting. Unfortunately I haven't been able to reproduce, which means it's likely something in your environment. I tried with the same OS, mountebank version, and nodejs version as you. One thing I could think of was if the second terminal session was using a different version of nodejs, but that also worked in my testing.

Can you think of anything else that could be unique in your environment? Lacking that, would you be wiling to jump on a Skype call to demonstrate the problem?

**Comment by bbyars** [comment]
Actually I'm pretty sure I know what's happening. `mb stop` needs to either be run in the same directory as the original `mb`, or needs to be given the path to the pidfile (e.g. `mb stop --pidfile ~/test/mb.pid`). Can you give that a shot and let me know? I'll update the docs to make that clearer.
