### ISSUE TITLE
Add automatic support for CORS on http/s imposters

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#184]
A few people have asked for help with CORS preflight requests. You can support it in mountebank by handling the OPTIONS request, but it has caused enough questions that it'd be good to bake it in.  Here's a recent response:

Reading https://www.html5rocks.com/en/tutorials/cors/, it looks like you'll need to set up an answer to the preflight that looks something like this:

The request they show is:

OPTIONS /cors HTTP/1.1
Origin: http://api.bob.com
Access-Control-Request-Method: PUT
Access-Control-Request-Headers: X-Custom-Header
Host: api.alice.com
Accept-Language: en-US
Connection: keep-alive
User-Agent: Mozilla/5.0...

and the response is

Access-Control-Allow-Origin: http://api.bob.com
Access-Control-Allow-Methods: GET, POST, PUT 
Access-Control-Allow-Headers: X-Custom-Header
Content-Type: text/html; charset=utf-8

which could work as something like this in mountebank (typed into email so probably JSON mistakes):

{
  "predicates": [{
    "equals": {
      "method": "OPTIONS"
    }
  }],
  "responses": [{
    "is": {
      "headers": {
        "Access-Control-Allow-Origin": "${ALLOW-ORIGIN}",
        "Access-Control-Allow-Methods": "GET, POST, PUT",
        "Access-Control-Allow-Headers": "${ALLOW-HEADERS}"
      }
    },
    "_behaviors": {
      "copy": [
        {
          "from": { "headers": "Access-Control-Allow-Origin" },
          "into": "${ALLOW-ORIGIN},
          "using": { "method": "regex", "selector": ".+" }
        },
        {
          "from": { "headers": "Access-Control-Allow-Headers" },
          "into": "${ALLOW-HEADERS},
          "using": { "method": "regex", "selector": ".+" }
        }
      ]
    }    
  }]
}

You don't have to use the copy behavior (which was just released this week and requires v1.8) if you want to hard-code for the specific request, but it allows you to always respond with what the client asked for. There's a few other options listed on the link above based on what the server provides.

**Comment by donhenton** [comment]
I do this myself, but what if I want the option to NOT have a CORS response?  would it be something like:

1. pass a useCORS flag to the server on start up
2. if flag present then use the copy stuff above to respond the the initial CORs request automatically
3. else  behave as was before this feature was introduced

Does that sound right?

**Comment by bbyars** [comment]
Yes that's exactly right, thanks for clarifying. This should be a root-level imposter configuration flag:

    {
        "protocol": "http",
        "port": 3000,
        "useCORS": true,
        "stubs": [...]
    }

**Comment by bbyars** [comment]
Should also remove the FAQ when implemented
