### ISSUE TITLE
Feature request: Expose state to injected predicates

### ISSUE THREAD

**Issue by gkohen** [bbyars/mountebank#187]
First of all let me thank you for creating this nifty server to make our testing much swifter.

I've moving to Mountebank from a Java server called Wiremock. Although there are some things in the previous server I did not like, I did heavily used the stateful capabilities:
http://wiremock.org/docs/stateful-behaviour/
What I wanted to achieve in Mountebank is the ability for a JS predicate to qualify a stub only if the server is in a certain state.
We currently do expose state to injected responses but not to predicates.
This might be useful in the cases that you have:
1. Get list of customers.
2. Add a customer through POST
3. Get the updated list.

You could also decide to have a certain stub that will put the system in a certain state and then the predicates can qualify stubs according to the new state.
@bbyars it would be great if you can give a guidance where should we store the state. Two options I thought of:
1. As part of the imposter and pass it down.
2. As a shared module that can hold a map of imposters to states.

**Comment by bbyars** [comment]
Thanks for the recommendation. I like the idea and will add it to the list.

**Comment by gkohen** [comment]
@bbyars, I'd like to work on a PR for this and had a question on direction. Let me know if I'm running with this the wrong way.
Thanks.

**Comment by bbyars** [comment]
Hi Gabriel,
Great! Happy to answer any questions you have, and if needed I can set up a
video call to walk through bits of gnarly code.
-Brandon

**Comment by gkohen** [comment]
@bbyars, thanks for the offer. To start with I'd like one of the to approaches to go about this in my previous comment. To be more specific:
1. Have a global module to hold a map to each predicate state and use that module in
