### ISSUE TITLE
Add homebrew package for installation

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#20]
Create a [homebrew formulae](http://brew.sh/) for mountebank with the self-contained package (node included).  Push to main repository so a simple `brew install mountebank` works on OSX.

**Comment by stavoxnetworks** [comment]
I will work on this if you want

**Comment by bbyars** [comment]
Thanks, please do if you have the bandwidth!

**Comment by stavoxnetworks** [comment]
In the process of building the formula for this, the command brew audit --debug --new-formula "mountebank" is necessary to obtain a SHA256 checksum, and perform some behind the scenes things. I am receiving an error during this portion of the creation that seems to be coming from rubocop. Please see the screenshot. Its almost if part of the path that rubocop is looking for is being truncated. However, I am not that familiar with Ruby. Have you seen this before?

![2020-11-15_00:25](https://user-images.githubusercontent.com/27533789/99177736-7013bd80-26da-11eb-9f5c-42e6d96ceab8.png)

**Comment by bbyars** [comment]
Sorry, that's a new error for me as well. I'm not sure what /ome refers to.

**Comment by bbyars** [comment]
Recently simplified installation options.
