### ISSUE TITLE
xpath won't match if namespaces contain capital letters

### ISSUE THREAD

**Issue by mkokott** [bbyars/mountebank#206]
#### Expected behaviour
Custom namespaces defined in predicates using xpath shouldn't be case sensitive. 

#### Actual behaviour
xpath doesn't evaluate correctly if a custom namespace in imposter definition contains upper case letters. 

#### Steps to reproduce
Define an imposter with a predicate using xpath that uses uppercase letters in a custom namespace:

`{
  "port": 4545,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "body": "A80135247"
          },
          "xpath": {
            "selector": "//ns2:userid",
            "ns": {
              "soap": "http://schemas.xmlsoap.org/soap/envelope/",
              "ns2": "http://www.SOMETHING.com"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "body": "xpath matched"
          }
        }
      ]
    }
  ]
}`

Send a matching XML request:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:du0="http://www.SOMETHING.com">
   <soapenv:Header/>
   <soapenv:Body>
      <du0:someservice>
         <du0:someoperation>
            <du0:service_information_in>
               <du0:userid>A80135247</du0:userid>
            </du0:service_information_in>
         </du0:someoperation>
      </du0:someservice>
   </soapenv:Body>
</soapenv:Envelope>`

The response body will be empty. Change the namespace to be all small letters:

`{
  "port": 4545,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "body": "A80135247"
          },
          "xpath": {
            "selector": "//ns2:userid",
            "ns": {
              "soap": "http://schemas.xmlsoap.org/soap/envelope/",
              "ns2": "http://www.something.com"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "body": "xpath matched"
          }
        }
      ]
    }
  ]
}`

Send the same XML request again and the body will be 'xpath matched'.

...

#### Software versions used

```
OS         : Windows 7 x64
mountebank : 1.8.0
node.js    : v5.0.0
  (only if installed via npm)
Installation method : 
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
info: [mb:2525] mountebank v1.8.0 now taking orders - point your browser to http://localhost:2525 for help
debug: [mb:2525] config: {"options":{"noParse":false,"nologfile":false,"allowInjection":false,"localOnly":false,"mock":false,"debug":false,"removeProxies":false,"heroku":false,"version":false,"help":false,"loglevel":"debug","configfile":".\
\imposter.json","port":2525,"pidfile":"mb.pid","logfile":"mb.log","ipWhitelist":["*"],"savefile":"mb.json"},"process":{"nodeVersion":"v5.0.0","architecture":"x64","platform":"win32"}}
info: [mb:2525] PUT /imposters
debug: [mb:2525] ::ffff:127.0.0.1:63430 => {"imposters":[{"port":4545,"protocol":"http","stubs":[{"predicates":[{"equals":{"body":"A80135247"},"xpath":{"selector":"//ns2:userid","ns":{"soap":"http://schemas.xmlsoap.org/soap/envelope/","ns2"
:"http://www.SOMETHING.com"}}}],"responses":[{"is":{"body":"xpath matched"}}]}]}]}
info: [http:4545] Open for business...
debug: [http:4545] ::1:63431 ESTABLISHED
info: [http:4545] ::1:63431 => POST /
debug: [http:4545] ::1:63431 => {"requestFrom":"::1:63431","method":"POST","path":"/","query":{},"headers":{"Host":"localhost:4545","Connection":"keep-alive","Content-Length":"443","Postman-Token":"84f361d2-af8b-120a-2f6e-0bc9e7bc0c5a","Cac
he-Control":"no-cache","Origin":"chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36","Content-Type":"text/plain;cha
rset=UTF-8","Accept":"*/*","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.8,de;q=0.6"},"body":"<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:du0=\"http://www.SOMETHING.com\">\r\n
  <soapenv:Header/>\r\n   <soapenv:Body>\r\n      <du0:someservice>\r\n         <du0:someoperation>\r\n            <du0:service_information_in>\r\n               <du0:userid>A80135247</du0:userid>\r\n            </du0:service_information_in
>\r\n         </du0:someoperation>\r\n      </du0:someservice>\r\n   </soapenv:Body>\r\n</soapenv:Envelope>"}
debug: [http:4545] ::1:63431 no predicate match
debug: [http:4545] ::1:63431 generating response from {"is":{}}
debug: [http:4545] ::1:63431 <= {"statusCode":200,"headers":{"Connection":"close"},"body":"","_mode":"text"}
debug: [http:4545] ::1:63431 CLOSED
```

**Comment by bbyars** [comment]
Just confirmed that [URL cases have to match](https://www.w3.org/TR/REC-xml-names/#NSNameComparison), so the bug is only about capital letters, not also about mismatched cases. Appears to be a bug in the xpath npm library, working on it now.

**Comment by bbyars** [comment]
Nope, the xpath module is fine. It has to do with the case insensitive matching code in predicates.js; the case transform isn't given to the namespace mapping.
