### ISSUE TITLE
Mountebank doesn't work with null values in JSON property

### ISSUE THREAD

**Issue by bazaka** [bbyars/mountebank#209]
#### Expected behaviour
Mountebank should return appropriate response if one of JSON properties is NULL

#### Actual behaviour
Mountebank returns incorrect response if one of JSON properties is NULL
...

#### Steps to reproduce
1. Create response with NULL property

```
"predicates": [
        {
          "equals": {
            "method": "post",
            "path": "/passwordreset",
            "body": {
              "UserId": "8169e7cf-bd0e-43ca-a56b-ada4f53980c5",
              "DisplayName": null,
              "EmailAddress": "existinguser@a.com"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 400,
            "body": "messageId"
          }
        }
```

2. Perform POST request with suggested body
3. Expected response: 400, Actual: 200

See attached screenshots for detailed explanation. 
...

#### Software versions used

```
OS         : Windows 10
mountebank : 1.6 and 1.9
node.js    : 6.7.0
![doesnt_work](https://cloud.githubusercontent.com/assets/8064136/23515784/f190d5b0-ff73-11e6-96b1-5f4e71015df0.png)
![works](https://cloud.githubusercontent.com/assets/8064136/23515783/f18de13e-ff73-11e6-8bb1-e86c9606302c.png)


  (only if installed via npm)
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```

**Comment by bbyars** [comment]
Thanks for reporting! I'll get this fixed soon.

**Comment by bbyars** [comment]
Fixed as of 3427a4f

**Comment by bazaka** [comment]
awesome! thanks for fast fixing!!

**Comment by bbyars** [comment]
Happy to do so. If you don't want to wait until the full release, you can
use an interim one from the test site
<http://mountebank-dev.herokuapp.com/docs/install>.

**Comment by bazaka** [comment]
There are no existing files on
http://mountebank-dev.herokuapp.com/docs/install

**Comment by bbyars** [comment]
Well that's embarrassing... I'll fix the links on the dev site shortly; in
the meantime you can do it yourself with a little touchup of the link it
provides you. For example:

https://s3.amazonaws.com/mountebank/v1.10.0
/mountebank-v1.10.0-beta.1386-darwin-x64.tar.gz

becomes

https://s3.amazonaws.com/mountebank/v1.10/mountebank-v1.10.0-beta.1386-darwin-x64.tar.gz
