### ISSUE TITLE
Error creating imposter with null value properties in nested property using DeepEquals predicate

### ISSUE THREAD

**Issue by bazaka** [bbyars/mountebank#229]
Can't create imposter with null value property located in nested property using DeepEquals predicate. See screenshots for detailed explanation.

![equalswithnullvalue](https://cloud.githubusercontent.com/assets/8064136/25176342/7b942ad4-2506-11e7-8432-341baec0a3c3.png)
![deepequalswithnullvalue](https://cloud.githubusercontent.com/assets/8064136/25176343/7b976c94-2506-11e7-8b5e-a4233a55f365.png)
![deepequalswithoutnullvalues](https://cloud.githubusercontent.com/assets/8064136/25176344/7b983be2-2506-11e7-8efd-9a47b6907051.png)

#### Expected behaviour
Mountebank should post imposter with null value using DeepEquals predicate

#### Actual behaviour
Error creating imposter using DeepEquals with null value
![deepequalswithnullvalue](https://cloud.githubusercontent.com/assets/8064136/25176501/f75fbcf0-2506-11e7-87e2-a37fd4691f18.png)

#### Steps to reproduce
1. Post imposter
`
{
  "port": 5009,
  "protocol": "http",
  "name": "DefaultMock",
  "stubs": [
    {
      "predicates": [
        {
          "deepEquals": {
            "method": "post",
            "path": "/email",
            "body": {
              "Type": "resetemailunknown",
              "Destination": [
                {
                  "UserId": null,
                  "Address": "unknownuser@test.com",
                  "Type": 1
                }
              ],
              "From": "test",
              "Subject": "Reset your password",
              "Body": "STR"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "body": "messageId"
          }
        }
      ]
    }
  ]
}
`

2. Error creating imposter
`{
  "errors": [
    {
      "code": "bad data",
      "message": "malformed stub request",
      "data": "Cannot convert undefined or null to object",
      "source": {
        "predicates": [
          {
            "deepEquals": {
              "method": "post",
              "path": "/email",
              "body": {
                "Type": "resetemailunknown",
                "Destination": [
                  {
                    "UserId": null,
                    "Address": "unknownuser@test.com",
                    "Type": 1
                  }
                ],
                "From": "test",
                "Subject": "Reset your password",
                "Body": "STR"
              }
            }
          }
        ],
        "responses": [
          {
            "is": {
              "statusCode": 200,
              "body": "messageId"
            }
          }
        ]
      }
    }
  ]
}`

#### Software versions used

```
OS         : Win10
mountebank : 1.9 and 1.10
```

Dockerfile:

```
FROM alpine:3.5

ENTRYPOINT ["mb"]
CMD ["start"]
ENV MOUNTEBANK_VERSION=1.10.0

RUN apk add --update nodejs
RUN npm install -g mountebank@${MOUNTEBANK_VERSION} --production
```

#### Log contents in mb.log when running mb --loglevel debug

```
info: [mb:2525] POST /imposters/
warn: [mb:2525] error creating imposter: [{"code":"bad data","message":"malformed stub request","data":"Object.keys called on non-object","source":{"predicates":[{"deepEquals":{"method":"post","path":"/email","body":{"Type":"resetemailunknown","Destination":[{"UserId":null,"Address":"unknownuser@test.com","Type":1}],"From":"test","Subject":"Reset your password","Body":"STR"}}}],"responses":[{"is":{"statusCode":200,"body":"messageId"}}]}}]
```

**Comment by bbyars** [comment]
Thanks for the detailed report! Fixed; I'll release it with v1.11 in the next couple days.
