### ISSUE TITLE
How to install Mountbank on Clouf foundry

### ISSUE THREAD

**Issue by pradeepkusingh** [bbyars/mountebank#232]
#### Expected behaviour
Want to install it in Cloud foundry platform and don't see any guidelines or instructions, can you please help?
...

#### Actual behaviour

...

#### Steps to reproduce

...

#### Software versions used

```
OS         :
mountebank :
node.js    :
  (only if installed via npm)
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```

**Comment by pradeepsingh1234** [comment]
Please help.

**Comment by bbyars** [comment]
Hi there,
I'd recommend asking this question on the [Google mailing list](https://groups.google.com/forum/#!forum/mountebank-discuss) to see if anyone has done something similar.
