### ISSUE TITLE
Create imposter using swagger file

### ISSUE THREAD

**Issue by stkac55** [bbyars/mountebank#238]
#### Expected behaviour

User would reference a swagger file and mb would parse the file to create an imposter with the required predicates and responses.  The functionality should be able to support a json or yaml swagger file.

**Comment by stkac55** [comment]
Based on our conversation @bbyars I will work on moving this functionality out of behaviors and into models or something more appropriate.   We'll work on this update and target the next release (1.12).

**Comment by bbyars** [comment]
Hey @stkac55 ,
One other thought occurred to me after we hung up. What about another tool does the generation? Have a look at https://www.npmjs.com/package/swaggerbank as an example (I say this without being very familiar with it; I didn't write it).

(added same comment on the wsdl issue)
-Brandon

**Comment by stkac55** [comment]
Hey @bbyars,

We've looked into the swaggerbank project and feel we can utilize some of what that project already has done with the creation of dummy data.  We found that our solution was a bit more updated in parsing all of the objects (request url paths, query parameters, headers, request, and response objects) specific to imposter creation.  The swaggerbank project had already developed some dummy data creation for the response based on static/semi-random generation of strings, integers, dates, etc that we adopted and can discuss any improvements.  

Based on our discussion a couple weeks back we moved the swagger feature out of behaviors and into the util directory.  Swagger can now be invoked while mb is running similar to how the mb save functionality was being referenced.  This is an example of creating an imposter from the cmd line or terminal:
```
mb swagger --swaggerfile filename.yaml --imposterport 3000
```

Let me know your thoughts we could always allow the swaggerfile to have two arguments (file name and port) instead of being invoked with two options.  Look forward to your thoughts, once we get the design hashed out for swagger we can use a similar implementation for wsdl/soap service creation.

**Comment by bbyars** [comment]
Thanks. I like the CLI, and would prefer to keep them as separate flags. One question: Is the --imposterport argument the port of a running instance of mb? If so, I'd just use --port, so it matches other CLI activities (like mb save) that require a running instance.

**Comment by stkac55** [comment]
The _imposterport_ argument is the port that the swagger imposter will be posted to.  The example above would create an imposter listening on port 3000.  Let me know if you need any further clarification.

**Comment by bbyars** [comment]
OK, I think I understand the difference now. So if you were running mb on port 8080 instead of the default 2525 and you wanted create an imposter based on swagger at port 3000, you'd run:

````
mb swagger --swaggerfile filename.yaml --port 8080 --imposterport 3000
````

Is that right? If so, it makes sense to me. One other question, and I think we already talked about it but I don't recall the answer. If the user needs to tweak the generated imposter with this approach, they'd have to save the imposter and recreate it, which biases me to thinking that simply saving the file is a cleaner option, separating generating the imposter configuration from creating the runtime imposter. I know you indicated this was a cleaner interface for you guys - can you remind me why?

**Comment by stkac55** [comment]
Yes, that's correct.  Overall the intent would be to have mb running on default port 2525 and post the imposter with specified port (3000 in our example) .  That would create a usable skeleton of the imposter with all response schemas defined from the swagger definition file. This is  a shortened example of a posted imposter with the petstore swagger example:

```
{
	"protocol": "http",
	"port": 3000,
	"numberOfRequests": 1,
	"name": "Swagger Petstore",
	"requests": [],
	"stubs": [{

			"responses": [{
				"is": {
					"statusCode": 200,
					"headers": {},
					"body": "[\n\t{\n\t\t\"id\": -40,\n\t\t\"category\": {\n\t\t\t\"id\": 2,\n\t\t\t\"name\": \"wodisenaci\"\n\t\t},\n\t\t\"name\": \"sohiobucam\",\n\t\t\"photoUrls\": [\n\t\t\t\"tubebomita\"\n\t\t],\n\t\t\"tags\": [\n\t\t\t{\n\t\t\t\t\"id\": 23,\n\t\t\t\t\"name\": \"hezammiwli\"\n\t\t\t}\n\t\t],\n\t\t\"status\": \"available\"\n\t}\n]"
				}
			}],
			"predicates": [{
				"matches": {
					"path": "/v2/pet/findByStatus",
					"query": {
						"status": "undefined"
					},
					"method": "get"
				}
			}]
		},
		{
			"responses": [{
				"is": {
					"statusCode": 400,
					"headers": {},
					"body": ""
				}
			}],
			"predicates": [{
				"matches": {
					"path": "/v2/pet/findByStatus",
					"query": {
						"status": "undefined"
					},
					"method": "get"
				}
			}]

		},
		{
			"responses": [{
				"is": {
					"statusCode": 200,
					"headers": {},
					"body": "{\n\t\"id\": -36,\n\t\"petId\": 17,\n\t\"quantity\": 30,\n\t\"shipDate\": \"2017-06-09T15:02:19-04:00\",\n\t\"status\": \"placed\",\n\t\"complete\": false\n}"
				}
			}],
			"predicates": [{
				"matches": {
					"path": "/v2/store/order",
					"method": "post",
					"body": {
						"id": "\\d+$",
						"petId": "\\d+$",
						"quantity": "\\d+$",
						"shipDate": ".+",
						"status": ".+",
						"complete": true
					}
				}
			}]
		},
		{
			"responses": [{
				"is": {
					"statusCode": 400,
					"headers": {},
					"body": ""
				}
			}],
			"predicates": [{
				"matches": {
					"path": "/v2/store/order",
					"method": "post",
					"body": {
						"id": "\\d+$",
						"petId": "\\d+$",
						"quantity": "\\d+$",
						"shipDate": ".+",
						"status": ".+",
						"complete": true
					}
				}
			}]
		}
	],
	"_links": {
		"self": {
			"href": "http://localhost:2525/imposters/3000"
		}
	}
}
```

**Comment by bbyars** [comment]
Looks good to me

**Comment by bbyars** [comment]
Think this is best done with an outside tool
