### ISSUE TITLE
Create imposter using WSDL file

### ISSUE THREAD

**Issue by stkac55** [bbyars/mountebank#239]
#### Expected behaviour
User would reference a wsdl file and mb would parse the file to create an imposter with the required predicates and responses. The functionality should be able to support http and https protocols.

**Comment by bbyars** [comment]
Hey Stephen,
One other thought occurred to me after we hung up. What about another tool does the generation? Have a look at https://www.npmjs.com/package/swaggerbank as an example (I say this without being very familiar with it; I didn't write it).
-Brandon

**Comment by bbyars** [comment]
Think this is best done with an outside tool
