### ISSUE TITLE
Broken fragment links on site

### ISSUE THREAD

**Issue by lyricnz** [bbyars/mountebank#248]
http://www.mbtest.org/docs/api/proxies to
http://www.mbtest.org/docs/api/proxies#predicateGenerators (line 151)
http://www.mbtest.org/docs/api/proxies#modes (line 163)

http://www.mbtest.org/docs/commandLine to
http://www.mbtest.org/docs/commandLine#templating (line 184)

**Comment by bbyars** [comment]
Thanks! I'm assuming the commandLine link was on the injection page, which was the only place I saw "#templating".

I still need to get https://github.com/bbyars/mountebank/issues/87 done before the accordian sections will open up when clicking the fragment links.
