### ISSUE TITLE
Export additional mountebank methods

### ISSUE THREAD

**Issue by patthiel** [bbyars/mountebank#253]
Currently, mountebank only exports the `create()` method.

It would be helpful if we could export more of the mountebank methods that match the current command line capabilities ([start, stop, save, restart, replay](https://github.com/bbyars/mountebank/blob/master/bin/mb#L251)).

I realize, this may be philosophically where the language bindings should come in, but since it's already written in JS I feel like it makes most sense to just do it here.

**Comment by bbyars** [comment]
Yes, I agree that if you're using JavaScript, you should be able to start it in-process. Thanks for the recommendation.

**Comment by bbyars** [comment]
After review, unfortunately the methods you're wanting exported (matching the CLI) are handled by the mb script itself (bin/mb in the code), which does a lot of process management. The mountebank.js file effectively acts as the entry point, and exports `create` as you point out, but has no understanding of the CLI functions you're looking for. CLI functions like `replay` use out of band API calls to function.

Unfortunately, that means that, while you can bind in process by creating mountebank.js directly, you'd have to recreate the CLI capability.
