### ISSUE TITLE
Mountebank converting the headers to lower case, where as application sends as upper case.

### ISSUE THREAD

**Issue by agnibrata** [bbyars/mountebank#256]
#### Expected behaviour
"headers": {
              "Connection": "close",
              "Date": "Thu, 29 Jun 2017 14:17:15 GMT",
              "Server": "xxxx Real-Time Server 1.0",
              "Content-Type": "text/plain",
              "Content-Length":"384"
            }

#### Actual behaviour
headers:  {
  'connection': 'close',
  'date': 'Thu, 29 Jun 2017 14:17:15 GMT',
  'server': 'xxxx Real-Time Server 1.0',
  'content-type': 'text/plain',
  'content-length': '384' }

#### Steps to reproduce

Recorded headers with upper case, but the mountebank is sending the response as lower case.

#### Software versions used

```
OS         :  RHEL7
mountebank : v10.x.x
node.js    : v6.x.x
  (only if installed via npm)
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here from mb.log
{"level":"debug","message":"[http:10221 XXXXGetMessages] ::ffff:127.0.0.1:59284 <= {\"statusCode\":200,\"headers\":{\"Connection\":\"close\",\"Date\":\"Thu, 29 Jun 2017 14:17:15 GMT\",\"Server\":\"XXXX Real-Time Server 1.0\",\"Set-Cookie\":\"DispatchInfo=CurrentServer%3Dccloud-linux00702.(none)%3A7210%26BackupServer%3D%26DispatchGroupVersion%3D3; path=/\",\"Content-Type\":\"text/plain\",\"Content-Length\":384},"timestamp":"2017-06-29T15:42:16.878Z"}
```

**Comment by agnibrata** [comment]
Got the issue resolved its seems, our nodeJs application is converting it to lowercase.

**Comment by bbyars** [comment]
Yes, node does that by default. I had to add code in mountebank to maintain
header case:
https://github.com/bbyars/mountebank/blob/master/src/models/http/headersHelper.js
