### ISSUE TITLE
Add ability to define predicate operator in predicateGenerators

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#257]
From https://groups.google.com/forum/#!topic/mountebank-discuss/5E_JU4R6sDE

The current set of predicateGenerators automatically decide between deepEquals and equals predicate operators, removing the ability, for example, to generate a predicate that simply asserts the existence of an XML tag. Add an optional `predicateOperator` field to let the user specify the operator.

For example:

````
"predicateGenerators": [{
  "matches": { "body": true },
  "xpath": { "selector": "//x" },
  "predicateOperator": "exists"
}]
````

Should generate:

````
"predicates": [{
  "exists": { "body": true },
  "xpath": { "selector": "//x" }
}]
````

**Comment by cgrad01** [comment]
@bbyars taking a look at this.
