### ISSUE TITLE
Matches predicate doesn't not work with reges Path

### ISSUE THREAD

**Issue by bazaka** [bbyars/mountebank#259]
#### Expected behaviour

Request to the some path with regex should return a response

#### Actual behaviour

Request to the some path with regex does not return a appropriate response

#### Steps to reproduce

1. Create mock
` {
      "predicates": [
        {
          "matches": {
            "method": "get",
            "path": "^/user/27117fc8-15ab-49c0-922d-d501c721596c.+$"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "body": [
              {
                "SessionId": "b0c7d7e7-ae60-45a7-9524-39fa1b3b6c5d",
                "UserId": "27117fc8-15ab-49c0-922d-d501c721596c",
                "TrackingId": "d0e444da-c052-4217-aa37-55757a60f724",
                "AuthenticationType": 1,
                "Started": "2017-06-30T02:00:08.3308082+03:00",
                "Closed": "2017-06-30T03:00:08.3308082+03:00",
                "IpAddress": null,
                "UserAgent": null,
                "Version": 1
              }
            ]
          }
        }
      ]
    },`

2. Perform request to
Request starting HTTP/1.1 GET http://mockedservice:5000/user/27117fc8-15ab-49c0-922d-d501c721596c?begin=2017-06-27T13:12:36.9677111Z&end=2017-07-04T13:12:36.9677111Z&limit=50

3. Matches predicate is not found

#### Software versions used

```
OS : Win10
mountebank : 1.11
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```

**Comment by bbyars** [comment]
Hi there,
Thanks for providing the necessary information to troubleshoot. The problem is the ".+" near the end of your regex, which is a regex way of describing one or more characters. Your actual request ends in 596c, but the matches predicate requires a path ending in 596c _and at least one more character_. Removing the .+ should do the trick.
