### ISSUE TITLE
Mountebank Proxy once not working with new docker version (Version 17.06.0-ce-mac18 (18433)

### ISSUE THREAD

**Issue by mthendral** [bbyars/mountebank#260]
#### Expected behaviour

...

#### Actual behaviour

...

#### Steps to reproduce

...
Mountebank  with mhart/alpine-node:7
Docker : Version 17.06.0-ce-mac18 (18433)
OS : Mac
node.js : 7.10

OS         : OS X El Captain
mountebank : 1.11.0
node.js    :
  7.10.0
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

<!--
Please review before pasting to ensure no sensitive data is copied
-->

```

error: [http:8081 {{servicename}}] ::ffff:172.18.0.3:36930 X=> {"code":"invalid proxy","message":"Cannot resolve \"http://{{server }}\””,”name":"Error","stack":"Error\n    at Object.from (/usr/lib/node_modules/mountebank/src/util/inherit.js:15:17)\n    at createError (/usr/lib/node_modules/mountebank/src/util/errors.js:10:26)\n    at Object.InvalidProxyError (/usr/lib/node_modules/mountebank/src/util/errors.js:25:16)\n    at ClientRequest. (/usr/lib/node_modules/mountebank/src/models/http/httpProxy.js:164:40)\n    at Object.onceWrapper (events.js:293:19)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:191:7)\n    at Socket.socketErrorListener (_http_client.js:358:9)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:191:7)"}

```

**Comment by bbyars** [comment]
Hi there,
This doesn't appear to be a mountebank issue so much as a Docker configuration issue with the network bridging. The error is correct in that "http://{{server }}\" is not a valid proxy; it's the Docker configuration that isn't setting {{server }} correctly.

Closing the issue based on that understanding; let me know if I've misunderstood.
