### ISSUE TITLE
Is it possible to configure mb not to record traffic when working as a proxyAlways mode?

### ISSUE THREAD

**Issue by nottyo** [bbyars/mountebank#284]
#### Expected behaviour
Sometimes, I don't want Mountebank to capture HTTP/HTTPS traffic when working as a **proxyAlways** mode because I just want to get the response from the origin server and pass through the client. So does Mountebank support for this situation?

...

#### Actual behaviour
As far as I know, Mountebank always capture every traffic when working as a proxy mode.
...

#### Steps to reproduce
1. Given configuring Mountebank as a **proxyAlways** mode
```
"stubs": [{
  "responses": [{
    "proxy": {
      "to": "http://origin-server.com",
      "mode": "proxyAlways"
    }
  }]
}]
```
2. When making a request to Mountebank and let it work as a proxyAlways mode.
3. Then Mountebank will automatically capture the traffic for you.
...

#### Software versions used

```
OS         : macOS
mountebank : 1.12.0
node.js    : 8.2.1
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

**Comment by bbyars** [comment]
Hi there,
This is not currently possible. I'll take this as a feature request to add
a flag to the proxy to prevent recording.
-Brandon

**Comment by bbyars** [comment]
Solved with https://github.com/bbyars/mountebank/pull/321
