### ISSUE TITLE
Change injection functions to accept an object

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#294]
As injection functions have expanded in functionality, they've accrued additional parameters, making the signature feel ad-hoc. You may need the fourth parameter but not the third, and why are there so many parameters anyhow?

I'd like to convert all injection functions to accept a single object parameter that contains fields for the current values. For response injection, for example, the current signature is:

````
function (request, state, logger, callback, imposterState) {...}
````

And the fifth `imposterState` parameter is undocumented, added way back when in a PR. Other new parameters will likewise just get shoved in at the end. I'd like to transform the signature to a single object containing the appropriate fields:

````
function (config) {
  // config.request
  // config.state
  // config.logger
  // config.callback
  // config.imposterState
}
````

For backwards compatibility, the old interface needs to still work. My preference would be to fix it in the `upcast` function in `compatibility.js`, as I'd like to centralize all backwards compatibility logic where possible.

The full list of injection functions can be found by searching for the literal string "eval(" and includes:
* response injection (responseResolver.js)
* advanced wait behavior (behaviors.js)
* decorate behavior (behaviors.js)
* predicate injection (predicates.js)
* tcp endOfRequestResolver (tcp.js)

**Comment by bbyars** [comment]
Copying Igor Korobka's question:

Hi,

Is there a way to inject imposter port into the stubbed response? I'm trying to virtualize a configuration service that returns URLs to some other configuration files. To make it work with mountebank I'd need to compose each URL with {imposter-hostname}:{imposter-port}. I can workaround the hostname part by using "localhost" but can't seem to find a way to inject the port part.

I'm creating imposters via mountebank REST API.

Would appreciate any assistance!

**Comment by bbyars** [comment]
Merge the injectionState and imposterState for responses

**Comment by jonscottclark** [comment]
Hey @bbyars , I think the code example for `addDecorateBehavior` (here: http://www.mbtest.org/docs/api/proxies#proxy-add-decorate-behavior) still refers to the old arguments `(request, response)`

**Comment by bbyars** [comment]
Thanks!
