### ISSUE TITLE
Feature: `mb reload --configfile`

### ISSUE THREAD

**Issue by ruudk** [bbyars/mountebank#296]
I run `mountebank` in a Docker (using docker-compose). I use `mb save --savefile data.json` to store the imposters/predicates to a file. I then modify this file locally.

It would be great if I could use the reverse method to reload mb from the configfile.

**Comment by bbyars** [comment]
You can.  It's "mb restart --configfile data.json"

-Brandon

**Comment by ruudk** [comment]
The issue is, that in a Docker container, the docker container's process is `mb`. When you call `mb restart` it will kill the process (to try to restart it). But starting won't work because when the process stops, the docker container is stopped.

**Comment by ruudk** [comment]
Actually, it would be better if Mountebank would always just scans for file changes and reloads automatically.

**Comment by gribok** [comment]
Are you able to put this hot reload feature back on roadmap?  

I experienced the same behavior. 
As I do changes in the esj files, I have to reload mountebank.

**Comment by gribok** [comment]
I found a good workaround via REST API in  
https://github.com/telekom/mb-netmgmt/blob/53c73b7bc46682923a7f59ede8bc7dd807117717/mb_netmgmt/__init__.py#L58

You send always a PUT in an infinite loop with your imposter configuration to emulate a "hot reload".

**Comment by bbyars** [comment]
Thanks for posting the workaround!
