### ISSUE TITLE
Support ignoring certain keys in predicateGenerators

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#300]
Let's say you had a proxy listening on port 3000 configured like this:

````
{
  "to": "http://origin-server.com",
  "predicateGenerators": [{
    "matches": { "query": true },
    "ignore": { "query": "startDate" }
  ]}
}
````

Then we get a request:

````
http://localhost:3000/path?limit=100&enhanced=true&startDate=2017-09-07&endDate=2017-10-11
````
 
The saved predicate should not have the `startDate` key.

Requested by Sabari Karthik.

**Comment by gePower** [comment]
Hi, can you assign me to the issue?

**Comment by bbyars** [comment]
Done!

**Comment by gePower** [comment]
thanks ! 
it's already done ! 
https://github.com/bbyars/mountebank/pull/661
