### ISSUE TITLE
lookup[].fromDataSource.csv : Not able to parse large json from csv. Getting error.

### ISSUE THREAD

**Issue by vijay-nts** [bbyars/mountebank#306]
[Categories.csv.zip](https://github.com/bbyars/mountebank/files/1424470/Categories.csv.zip)

#### Expected behaviour

Response from attached CSV file has to be delivered (CSV file have statuscode, response, method and device  data stored)

...

#### Actual behaviour

      throw er; // Unhandled 'error' event
      ^

Error: Invalid opening quote at line 2
    at Error (native)
    at Parser.__write (/usr/local/lib/node_modules/mountebank/node_modules/csv-parse/lib/index.js:406:15)
    at Parser._transform (/usr/local/lib/node_modules/mountebank/node_modules/csv-parse/lib/index.js:181:10)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Parser.Writable.write (_stream_writable.js:243:11)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
USMB102372:Mountebank vijayakumar_k$ 

...

#### Steps to reproduce
--------
Attached CSV file as zip for reference.

-------Here is my imposter----

{
  "port": 9595,
  "protocol": "http",
  "stubs": [
    {
      "responses": [
        {
          "is": {
            "statusCode": "${row}['StatusCode']",
            "body": "${row}['Response']"
          },
          "_behaviors": {
            "lookup": [{
              "key": {
             "from": { "query": "device" },
              "using": { "method": "regex", "selector": "(.*)"  }},
              "fromDataSource": {
                "csv": {
                  "path": "categories.csv",
                  "keyColumn": "device"
                }
              },
              "into": "${row}"
            }]
          }
        }
      ],      "predicates": [
        {
          "and": [
            {
              "equals": {
                "method": "POST"
              }
            },
            {
              "contains": {
                "path": "/categories"
              }
            }
          ]
        }
      ]
    }
  ]
}
------------------------

I am making post call with the following Request Body and trying to lookup device as a key and usng this key, trying to build response from csv.But it is failing I am getting error as I have long json file as repsonse in csv.It works fine with simple json response stored in csv.

URL : http://localhost:9595/product/categories?device=desktop
Method : POST
Request Body 
...

#### Software versions used

```
OS         : MAC - 10.12.5
mountebank :v1.12.0
node.js    : v6.11.1
  (only if installed via npm)
Installation method :npm
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```
info: [mb:2525] mountebank v1.12.0 now taking orders - point your browser to http://localhost:2525 for help
debug: [mb:2525] config: {"options":{"loglevel":"debug","configfile":"./products.ejs","port":2525,"noParse":false,"pidfile":"mb.pid","nologfile":false,"logfile":"mb.log","allowInjection":false,"localOnly":false,"ipWhitelist":["*"],"mock":false,"debug":false,"heroku":false},"process":{"nodeVersion":"v6.11.1","architecture":"x64","platform":"darwin"}}
info: [mb:2525] PUT /imposters
debug: [mb:2525] ::ffff:127.0.0.1:61398 => {"imposters":[{"port":9595,"protocol":"http","stubs":[{"responses":[{"is":{"statusCode":"${row}['StatusCode']","body":"${row}['Response']"},"_behaviors":{"lookup":[{"key":{"from":"body","using":{"method":"jsonpath","selector":"$..productId"}},"fromDataSource":{"csv":{"path":"Products_results.csv","keyColumn":"prodtid"}},"into":"${row}"}]}}],"predicates":[{"and":[{"equals":{"method":"POST"}},{"contains":{"path":"/productdetails/_search"}}]}]},{"responses":[{"is":{"statusCode":"${row}['StatusCode']","body":"${row}['Response']"},"_behaviors":{"lookup":[{"key":{"from":{"query":"device"},"using":{"method":"regex","selector":"(.*)"}},"fromDataSource":{"csv":{"path":"VPD_categories.csv","keyColumn":"device"}},"into":"${row}"}]}}],"predicates":[{"and":[{"equals":{"method":"POST"}},{"contains":{"path":"/search/categories"}}]}]}]}]}

**Comment by vijay-nts** [comment]
Thanks byars ..Any timeline when can we get this implemented?

**Comment by bbyars** [comment]
Hi there,
Aiming for this next release which should be out by end of year. I'll let
you know if it gets fixed before then in case you want to use a pre-release
in the interim.
-Brandon

**Comment by vijay-nts** [comment]
Thank You..

**Comment by bbyars** [comment]
Hi there,
Sorry for the painfully slow response. The problem appears to be that the file isn't actually a CSV file. The 2nd field (Response) is, effectively, "{\"categories\":[{\"type\":\"Tier1\"". The comma separating the next field indicates a new CSV column. To fix it, you'd have to quote the whole JSON, which means escaping all the quotes (as I did above).
