### ISSUE TITLE
Docker > Create new build for v1.13.0

### ISSUE THREAD

**Issue by ruudk** [bbyars/mountebank#307]
Thanks for tagging v1.13.0. Could you issue a new build on https://hub.docker.com/r/andyrbell/mountebank/tags/?

🙏 Thanks 💯

**Comment by bbyars** [comment]
Looks like Andy Bell manages that process. I see the v1.13.0 tag there now.

**Comment by ruudk** [comment]
Yep, I was confused. Thought it was coming from you.
