### ISSUE TITLE
TCP mock

### ISSUE THREAD

**Issue by jurijshevtsov** [bbyars/mountebank#314]
[mb.log](https://github.com/bbyars/mountebank/files/1501101/mb.log)
#### Expected behaviour

curl -i -X POST -H 'Content-Type: application/json' http://localhost:2525/imposters --data '{
  "port": 5557,
  "protocol": "tcp",
  "mode": "text",
  "stubs": [{
    "responses": [
      { "is": { "data": "12345qwerasdf" }}
    ],
    "predicates": [{ "contains": { "data": "111;700;0;525-28-16;*;" } }]
  }]
}'

1. ~$ echo "111;700;0;525-28-16;*;" | nc localhost 5557
12345qwerasdf = OK

2.  #!/bin/bash
HOST=127.0.0.1
PORT=5557
resp="111;700;0;525-28-16;*;"
echo $resp
exec 3<>/dev/tcp/${HOST}/${PORT}
echo $resp 1>&3
echo "1"
cat <&3 > res1251.txt
echo "2"

= timeout

#### Software versions used
mountebank v1.13.0
OS = Ubuntu 16.04
Installation method :deb

**Comment by bbyars** [comment]
Thanks for reporting. I'm hoping you can give me some help on understanding the issue - your bash skills far exceed mine ;>

Let me take the script and comment on it to see if I understand the intent. Comments below represent my understanding, can you confirm or correct?

````
#!/bin/bash
HOST=127.0.0.1
PORT=5557
resp="111;700;0;525-28-16;*;"
echo $resp

# Replace stdin and stdout with the device file as file descriptor 3?
# I assume that debian auto-creates a device file for the tcp socket
exec 3<>/dev/tcp/${HOST}/${PORT}

# This challenges my understanding of the above comment. I thought that
# the statement above auto redirects subsequent stdin (and stdout) to fd 3,
# but here it looks like you're redirecting again. I think this redirects stdout
# to fd 3. Is this the same as the following, if the line above was missing?:
#     echo $resp > /dev/tcp/${HOST}/${PORT}
echo $resp 1>&3

# So again, I'm probably misunderstanding exec, but I believe this sends
# the echoed statement to /dev/tcp/${HOST}/${PORT}, no?
echo "1"

# Read the contents of /dev/tcp/${HOST}/${PORT} and send to res1251.txt,
# equivalent to:
#   cat /dev/tcp/${HOST}/${PORT} > res1251.txt
# How is the device file supposed to work? In other words, what are you
# expecting here?
cat <&3 > res1251.txt

# Send echoed statement to /dev/tcp/${HOST}/${PORT}
# What are you expecting here?
echo "2"
````

I've likely misinterpreted some of it, but the main thing I'm looking for is why some of those statements are in there and what you're expecting.
