### ISSUE TITLE
Why is logging to console so restricted?

### ISSUE THREAD

**Issue by skormos** [bbyars/mountebank#318]
#### Expected behaviour

Should be able to pipe to another process, a la:
`mb --nologfile | awk '...'`

...

#### Actual behaviour
https://github.com/bbyars/mountebank/blob/69b551c28b1553c35877a4947c64a236a07e6538/src/mountebank.js#L68-L71

removes the Console transport if `stdout` is writing to anything other than terminal.

...

#### Software versions used

```
OS         :  macOS Sierra 10.12.6
mountebank : 1.13
node.js    : 8.4+
  (only if installed via npm)
Installation method : npm i -g
  (npm, zip, tar, pkg, deb, rpm)
```

Writing to `stdout` is a _12-Factor App_ characteristic, however, the deployer of the application should not be constrained to just output to the terminal, or as is formatting from the application.

**Comment by rhetzler** [comment]
@bbyars i came across mountebank yesterday and love it already.

helpful tip for anyone trying to get logs while running this in docker: allocating a tty should resolve this. in docker-compose, you can do this by adding
```tty: true```

If docker support (per microservices, testing, etc) is a desired objective of mountebank, I recommend seriously considering this as a basic feature, not power user.

**Comment by bbyars** [comment]
I removed the tty check; will be released with v15
