### ISSUE TITLE
Imposters Injection: Unable to define script to inject in imposters while stubbing binary object over TCP

### ISSUE THREAD

**Issue by deepak-itneer** [bbyars/mountebank#320]
Hello,

I have a simple java TCP client application and a server application. Client sends serialized object from client and received on server. Server sends a serialized object as response and received that response on client application.

I want to mock the server responses using mountebank. And for that I have to add imposter in mountebank like as follows:
{
  "port": 8087,
  "protocol": "tcp",
  "mode": "binary",
  "stubs": [{
    "responses": [{ 
    	"proxy": {
    		"to": "tcp://localhost:8088",
    		"predicateGenerators": [{
    			"matches": {
    				"path": true,
    				"method": true,
    				"query": true
    			}
    		}],
    		"mode": "proxyAlways"
    	}	
    }]
  }],
  "endOfRequestResolver": {
    **_"inject": ""_**
  }
}

But for **_"inject"_** property in **_"endOfRequestResolver"_**, I need to add some node.js fuction to match the end of request condition.

Please suggest me, what script should be used to match end of request condition.

Thanks In Advance.

**Comment by bbyars** [comment]
Hi there,
First a point unrelated to your question: the predicateGenerators you've
defined won't do anything for you. Those are HTTP request fields, not TCP,
so while they won't prevent you from capturing any data (I think), they
won't actually do anything either.

Now to your specific question -- unfortunately there's no generic answer.
TCP isn't actually an application protocol; it's the transport protocol
behind a whole ecosystem of application protocols. Some of those are
universally used with well documented ways of determining the end of a
request (HTTP fits the bill). Some are custom-written within an enterprise.
I'd try the following:

   - Leaving the endOfRequestResolver off. For small messages, the default
   approach of using a packet per request probably works, although you'll get
   very wonky data once that fails
   - If you're using a custom application protocol, see if you can look at
   the code to determine how the request ends
   - If you're using a standard protocol, you'll have to do a little
   research to see if you can find a library that does it for you. Chapter 9
   of my book
   <https://www.manning.com/books/testing-microservices-with-mountebank> shows
   how to do this with .NET Remoting, and you can find the code for it
in the source
   code for the chapter
   <https://github.com/bbyars/mountebank-in-action/tree/master/ch09>.

-Brandon
