### ISSUE TITLE
Feature request: optional "sleep" attribute to mock long-lasting requests

### ISSUE THREAD

**Issue by bligny** [bbyars/mountebank#324]
We are intensively using mountebank in our ESB to mock external systems.
We would like to also use it for **stress/load tests**, in order to see how our ESB behaves when some of these external components are getting slow.
To do this, we need to be able to model some kind of **duration** on the stubs (response level).

IMHO it would be quite easy to introduce an (optional, with 0 as default value) "sleep" attribute indicating how much time an imposter has to wait before returning the response.

**Comment by bbyars** [comment]
Good news! The wait behavior does this already: http://www.mbtest.org/docs/api/behaviors. You can also automatically capture real downstream latencies during proxying with the addWaitBehavior.

Take a look at those and let me know if there's more needed for your use case. If not, I'll close this issue.
-Brandon

**Comment by bligny** [comment]
Aargh, shame on me, I should have (fully) read the documentation :-(
Well, it seems Mountebank already provides everything I need for my use case.
So I think you can close the issue.
Sorry for the noise,
Bernard.
