### ISSUE TITLE
gRPC Protocol Support

### ISSUE THREAD

**Issue by quicksnap** [bbyars/mountebank#327]
Looking at the internals of mountebank, I feel I could implement gRPC support without much trouble. I'm not sure the best approach to model a gRPC virtualized server, though!

With HTTP, any well-formed response is OK, so a simple `is` stub response is fine for any given request. With gRPC, however, a single server listens for multiple Services, and each Service contains multiple RPCs. Each RPC message must be well-formed (the correctly encoded protobuf message).

My uncertainty is how Mountebank would express this as an Imposter/Stub. Constraining the Imposter only to a single gRPC Service would break the protocol. But allowing multiple Services breaks the `is` stub, since a single `is` cannot be generic--it _requires_ a Service+Message predicate.

I realize you may not work with gRPC, but wanted to put up some thoughts here anyway.

Thanks for all the work on this project! The code is pretty great--really easy to dig into.

**Comment by bbyars** [comment]
Thanks for looking into it. You're right, I've never worked with gRPC and have very little familiarity with it, so I appreciate the added context.

The advantage of creating a separate protocol is that you get to define the request and response JSON structures for it that mountebank uses. Would a more complex JSON response structure solve the problem?

HTTP's response structure looks something like this:

````
{
  "statusCode": 200,
  "headers": {},
  "body": "..."
}
````

What about something like this for gRPC (I realize I'm butchering this, so I'm going to beg you never to ascribe to malice that which can be explained as pure incompetence):

````
{
  "services": {
    "Greeter": {
      "messages": {
        "SayHello": {
          ...
        },
        "SayGoodbye": {
          ...
        }
      }
    }
  }
}
````

That's a bit of a loose schema. The `services` and `messages` would be generic; the service key names and message key names would be specific to each imposter, and the bit in the ellipsis could be whatever is needed to support the .proto schema for that server. If it helps, we could even add some top-level imposter configuration that helps define the schema. If something like that is even close to being correct, then the `is` response structure would effectively include a set of services and messages inside of it, which solves two problems:

* You don't have to check whether it has the correct predicates,
* One response could support a number of messages

I'll leave it to you to tell me if that's a good idea or not, it's just the one that came to mind as you described the problem.

If it doesn't work, the next option, I think, would be to raise the white flag on the `is` response type and recognize that other protocols require a different response type. I'd prefer to explore other options before adding additional abstractions, but I'm not morally opposed to the idea.

**Comment by quicksnap** [comment]
I agree that it's too soon the discard `is`.

I haven't had a good amount of time to consider the edge cases on the `services{ Greeter {...}}` type object. When I was tossing around ideas before opening this issue, I think I may have considered that approach. One red flag may have been that the actual "services" seem to semantically belong in the imposter definition, but that may not be the case.

I'll try to revisit it all this week! Thanks for your thoughts.

**Comment by GeorgeBills** [comment]
I'd also be very interested in GRPC support, mocking out GRPC based services would save me a lot of pain with the work I'm doing. I'm assuming by GRPC support we're talking about Protocol Buffers over GRPC since that's the default. I've been digging around in the code a bit and have a few thoughts, hoping a bit of a braindump is useful for someone.

In terms of modelling GRPC service requests and responses in an imposter JSON it'd be nice to align as closely as possible with the [canonical proto3:json encoding](https://developers.google.com/protocol-buffers/docs/proto3#json).

The hardest problem here is that you need some out of band definition of the proto message for a few things:

 * Field indexes. Protobuf messages don't store field names internally, just the numeric index of the field.

 * Types. You need to know the correct type to make calls to the [google-protobuf lib](https://github.com/protocolbuffers/protobuf/tree/master/js) BinaryReader / BinaryWriter. You can't infer the protobuf type from the type of the variable in the JSON since there are more types representable in a protobuf than JS has.

i.e. it's not useful to have a JSON defined request message like `{ "fooBar": v }` if you can't know that fooBar is the nth field in the protobuf, and that v should be encoded as a uint32 and not an int32.

One solution might be to define in the imposter JSON something that indicates the types and indexes for a request:

    "request": { "name": "Jane Doe", "age": 123, "fooBar": true },
    "fields": [
        { "n": "name" },
        { "n": "age", "t": "UINT32" },
        { "n": "fooBar", "t": "BOOL", "i": 7 } 
    }

I'm assuming that you could default to `"t": "STRING"` and infer the numeric indexes from the order in the array just to keep the definition as terse as possible, but sometimes you'll have skipped fields, out of a sensible order fields, etc, and you'll need to be able to specify the index explicitly. If we can rely on the JSON being parsed into a map and not an object (i.e. into something that preserves ordering) then you could get it even terser and just use the field name as the map key.

Another solution might be to require users to provide the original .proto files (they should have them if they're mocking out a service they're interfacing against) and dynamically compile them with [@grpc/proto-loader](https://www.npmjs.com/package/@grpc/proto-loader). I think requiring .protos would make dynamically POSTing new imposters hard or impossible though.

**Comment by GeorgeBills** [comment]
Turns out https://github.com/protobufjs/protobuf.js can parse a proto definition from JSON fairly easily. Would an imposter.json like the following be workable? The "protos" section is pretty close to "out of the box" compatible with protobuf.js which saves a lot of pain in parsing.

    {
      "host": "127.0.0.1",
      "port": 4545,
      "protocol": "grpc",
      "protos": {
        "helloworld": {
          "Greeter": {
            "methods": {
              "SayHello": {
                "requestType": "HelloRequest",
                "responseType": "HelloReply"
              }
            }
          },
          "HelloRequest": {
            "fields": {
              "name": { "type": "string", "id": 1 }
            }
          },
          "HelloReply": {
            "fields": {
              "message": { "type": "string", "id": 1 }
            }
          }
        }
      },
      "stubs": [
        {
          "predicates": [
            {
              "or": [
                { "method": ["helloworld", "Greeter", "SayHello"] },
                { "responseType": ["helloworld", "HelloReply" ] }
              ]
            }
          ],
          "responses": [
            { "is": { "reply": "Hello Fred!" }},
            { "is": { "reply": "Hello again Fred!" }},
            { "is": { "reply": "Don't you have somewhere to be?" }},
            { "error": { "code": 14, "message": "too many hello's" }}
          ]
        }
      ]
    }

**Comment by GeorgeBills** [comment]
I should have understood the predicate matching better before I stubbed out the above. I've got the below mostly working and it's much more "mountebank-y". @bbyars does this look ok as a starting point?

    "stubs": [
      {
        "predicates": [
          { "or": [
            { "equals": { "responseType": ["helloworld", "HelloReply" ] }},
            { "equals": { "methodName": "SayHello" }}
          ]},
          { "equals": { "request": { "name": "john smith" }}}
        ],
        "responses": [
          { "is": { "response": { "message": "Hello John!" }}},
          { "is": { "respose": { "message": "Hello again John!" }}},
          { "is": { "error": { "code": 14, "message": "too many hello's" }}}
        ]
      }
    ]

**Comment by bbyars** [comment]
Hi George -- that looks great to me!

**Comment by matehat** [comment]
The only thing preventing us from using mountebank heavily is gRPC support, so I’m glad this is in the works! Tell me if I can be of any help!

**Comment by GeorgeBills** [comment]
@matehat feel free to check out the branch above and give early feedback on if it meets your needs or not - as mentioned above I still need to write some proper doco in there, but I won't be able to get to it until the weekend at the earliest. If you copy paste the imposter.json above and then replace the stubs section with the latter you should get a running mb that handles calls from the "helloworld example" GRPC client.

**Comment by ArseniyAntonov** [comment]
@GeorgeBills  could you please add an example - how to use it. 
I would like to try but I can't understand what should I do )

**Comment by GeorgeBills** [comment]
@ArseniyAntonov sorry went radio silent for a bit there - I've attached the [GRPC protocol documentation](https://github.com/bbyars/mountebank/files/3488530/mountebank.-.grpc.pdf) as it is currently, but you'd need to have a rough idea of how Mountebank works before that's useful to you.

Basically you should be able to use it to mock out service(s) that the service you actually want to test relies on. Say you have service A you want to test, that talks to services X, Y and Z; hopefully you can use the GRPC proto support to mock out X, Y and Z, and then you can test service A locally without having to run heaps of services, databases, etc you don't care about.

**Comment by tommyongib** [comment]
Hi @GeorgeBills, any chance that you would create a PR soon so that everyone can give feedback and this feature can be released? I'm really interested to be able to use grpc in mbtest and hope if I could contribute somehow :)

**Comment by GeorgeBills** [comment]
@tommyongib sorry for the long period without a reply - I've moved on from the job where I was using GRPC and now I'm working with boring old REST. My boss never saw the point of mocking services out so I never got a chance to test that code in a real context. If I was bbyars I wouldn't want to merge a PR that no one's run for production real-life services.

What's on the [branch](https://github.com/GeorgeBills/mountebank/tree/grpc) worked with the hello world GRPC services I tested it with (i.e. literally the GRPC hello world with a few other field types thrown in), and there's rough doc on how to use it there (attached above). You could always pull the branch down, test it with your services and pick it up if it meets your needs?

**Comment by bbyars** [comment]
Closing as this is now community support through protocol extensions.

**Comment by samarth-gupta-traceable** [comment]
Hey @bbyars  when you say community protocol extension do you mean https://github.com/cbrz/mountebank-grpc , or was referring to https://github.com/grpc-ecosystem/grpc-gateway ,  or something totally different that I could not find via google search :)

**Comment by bbyars** [comment]
Hi Samarth,
I was referring specifically to the first one on your list:
https://github.com/cbrz/mountebank-grpc.
-Brandon

**Comment by taextreme** [comment]
Hello

I currently try to mock grpc service using https://github.com/cbrz/mountebank-grpc .

But look like the plugin is abandon and doesn't work anymore. I can't even npm install it on my machine.

**Comment by bbyars** [comment]
Thanks for the update. I'll remove it from the list.
-Brandon

**Comment by john801205** [comment]
For anyone who might be interested, I just created a plugin for the gRPC protocol to cater to my personal needs. Although it is still at an early stage, feel free to give it a try and provide your feedback. :)

https://github.com/john801205/mb-grpc
