### ISSUE TITLE
delete-imposter-requests method doesn't delete requests list

### ISSUE THREAD

**Issue by Glazz87** [bbyars/mountebank#340]
#### Expected behaviour

According to the http://www.mbtest.org/docs/api/overview#delete-imposter-requests i expect that when i use DELETE /imposters/:port/requests and following GET /imposters/:port i will recieve numberOfRequests = 0 and requests = [] (empty list).

#### Actual behaviour

DELETE /imposters/:port/requests and following GET /imposters/:port returns numberOfRequests = 0 and **requests = [:recordedRequests] (not empty list).**

#### Software versions used

```
OS         : Ubuntu 16.04.3 LTS
mountebank : 1.14.0
node.js    : 4.2.6
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

**Comment by ruudk** [comment]
I have the same issue here with 1.15.0

**Comment by bbyars** [comment]
Resetting the requests array and the numberOfRequests does not appear to be the intent of that endpoint. It was apparently designed to remove saved proxy responses and just had an awkward name that led to misunderstandings. I've renamed the endpoint DELETE /imposters/:port/savedProxyResponses to better reflect intent (leaving the old endpoint undocumented for backwards compatibility). It also seems like it may no longer be needed now that there is a proxyTransparent mode for proxies that doesn't save responses.

**Comment by jacktuck** [comment]
So is there a way to delete the requests array and reset numberOfRequests?

**Comment by bbyars** [comment]
Yes, it's implemented for the next release
