### ISSUE TITLE
Unable to create stub responses on the website

### ISSUE THREAD

**Issue by mdfarhanin** [bbyars/mountebank#348]
Unable to create stub responses on the website

#### Expected behaviour

Able to create stub responses on the website

#### Actual behaviour

Unable to create. Website is unresponsive , there is no content

#### Steps to reproduce

1. Go to http://www.mbtest.org/imposters
2. Click on Add Icon
3. Click on Add Icon under stubs
4. Click on the Add Icon under responses

#### Software versions used

```
OS         : MAC OS
mountebank : Website
node.js    :
  (only if installed via npm)
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

Used chrome, IE 8 and Safari

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```

**Comment by bbyars** [comment]
Duplicate of https://github.com/bbyars/mountebank/issues/35
