### ISSUE TITLE
Supporting matching by HTTP hostname

### ISSUE THREAD

**Issue by richardgavel** [bbyars/mountebank#355]
It would be nice if I could match an HTTP request by the hostname, as well as the path. This would allow a single instance of MB to serve as the mock for multiple different services (and not have to worry about path conflicts between those services.

**Comment by franzwong** [comment]
Can you match the "Host" header?

**Comment by bbyars** [comment]
Closing based on the Host header recommendation. Let me know if that's insufficient.
