### ISSUE TITLE
Supporting stubs for tcp that returns response after connected

### ISSUE THREAD

**Issue by trantienduchn** [bbyars/mountebank#366]
#### Expected behaviour
I want to create a tcp server on port 25 to be able act as a stubbed SMTP server. When using `nc  172.17.0.2 25`, expecting a configurable stub for connected response message

```
Trying 172.17.0.2...
Connected to 172.17.0.2.
Escape character is '^]'.
my_response_message_after_the_client_connected
```
...

#### Actual behaviour
When using `nc  172.17.0.2 25`

```
Trying 172.17.0.2...
Connected to 172.17.0.2.
Escape character is '^]'.

```
...

#### Steps to reproduce
- start moutbank on localhost
- create importer with an `inject` predicate, listening all events of tcp server
```
{
  "port": 25,
  "protocol": "tcp",
  "stubs": [
	{
      "predicates": [{"inject": "function(request, logger) {logger.info(dummy message); return false;}"}],
      "responses": [{ "is": {"data": "dummy message"}}]
    },
    {
      "predicates": [{"startsWith": {"data": "HELO"}}],
      "responses": [{ "is": {"data": "500 Syntax error, command unrecognised"}}]
    },
    {
      "predicates": [{"startsWith": {"data": "EHLO"}}],
      "responses": [{"is": {"data": "500 Syntax error, command unrecognised"}}]
    }
  ]
}
```
- `nc  localhost 25`
...

#### Software versions used

```
OS         : Linux Debian
mountebank : 1.3.0
node.js    :
  (only if installed via npm)
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug
I putted "--loglevel debug" but it didn't work. So i used the endpoint, notice that there is no `dummy message` printed out when tcp connected. "Inject" can't even catch the connected event.

```
{
    "logs": "[{\"level\":\"info\",\"message\":\"[mb:2525] mountebank v1.3.0 (node v0.12.2) now taking orders - point your browser to http://localhost:2525 for help\",\"timestamp\":\"2018-07-04T05:53:29.711Z\"},{\"level\":\"info\",\"message\":\"[mb:2525] POST /imposters\",\"timestamp\":\"2018-07-04T05:53:44.809Z\"},{\"level\":\"warn\",\"message\":\"[mb:2525] dry running injection, use the isDryRun request field in your JavaScript to ignore...\",\"timestamp\":\"2018-07-04T05:53:44.817Z\"},{\"level\":\"debug\",\"message\":\"[mb:2525] ::ffff:172.17.0.1:54160 => {\\\"port\\\":25,\\\"protocol\\\":\\\"tcp\\\",\\\"stubs\\\":[{\\\"predicates\\\":[{\\\"inject\\\":\\\"function(request, logger) {logger.info('dummy message'); return false;}\\\"}],\\\"responses\\\":[{\\\"is\\\":{\\\"data\\\":\\\"dummy message\\\"}}]},{\\\"predicates\\\":[{\\\"startsWith\\\":{\\\"data\\\":\\\"HELO\\\"}}],\\\"responses\\\":[{\\\"is\\\":{\\\"data\\\":\\\"500 Syntax error, command unrecognised\\\"}}]},{\\\"predicates\\\":[{\\\"startsWith\\\":{\\\"data\\\":\\\"EHLO\\\"}}],\\\"responses\\\":[{\\\"is\\\":{\\\"data\\\":\\\"500 Syntax error, command unrecognised\\\"}}]}]}\",\"timestamp\":\"2018-07-04T05:53:44.826Z\"},{\"level\":\"info\",\"message\":\"[tcp:25] Open for business...\",\"timestamp\":\"2018-07-04T05:53:44.834Z\"},{\"level\":\"debug\",\"message\":\"[tcp:25] ::ffff:172.17.0.1:38432 ESTABLISHED\",\"timestamp\":\"2018-07-04T05:53:48.737Z\"},{\"level\":\"info\",\"message\":\"[mb:2525] GET /logs\",\"timestamp\":\"2018-07-04T05:53:56.562Z\"}]"
}
```

**Comment by bbyars** [comment]
Hi there,
The behavior appears correct to me. You're not sending any data to the imposter, so it doesn't match any of your predicates and mountebank is sending back a default (empty) response. My tests sent back your responses correctly if I send data matching the predicate, for instance:

````
echo HELO | nc localhost 25
````

That sends back the correct message.

As far as logging all requests, the problem is you have a syntax error in your injection function. Add quotes around "dummy message" and it will log correctly.

Let me know if that doesn't solve the error for you.

**Comment by trantienduchn** [comment]
Sorry for that 😄 , that was copy & paste mistake. It was exactly `"dummy message"` in my injection. Anyway, is the any way to configure an imposter returns a message immediately after connecting to tcp server without using `echo HELO` as input of `nc localhost 25`?

**Comment by bbyars** [comment]
Yes that's right -- mountebank is very much meant to be used in "request-response" mode, not interactively over an open connection.

**Comment by mattnathan** [comment]
I would also like this functionality.

My use-case is to mock an external api (tcp but with a login prompt). The prompt is sent on connection. It would be really useful to be able to configure mountebank to send a response immediately on connect
