### ISSUE TITLE
mb.log getting renamed after the file size exhausted and it is not creating mb.log file again which is causing "Error: ENOENT: no such file or directory, open 'mb.log'"

### ISSUE THREAD

**Issue by anuu1989** [bbyars/mountebank#371]
#### Expected behaviour

Once mb.log is full it should it i renaming the mb.log ---> to mb1.log but not creating new log file named mb.log which is causing below error : 

Error: ENOENT: no such file or directory, open 'mb.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
  
#### Actual behaviour

Should create mb.log file if you log files size is exhausted 

#### Steps to reproduce

Exhaust the mb.log file size

#### Software versions used

```
OS         : Mac os
mountebank :
node.js    :
  (only if installed via npm)
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```

**Comment by bbyars** [comment]
Appears to be an issue with winston. Bumped up log to 20m and use tailable logs
