### ISSUE TITLE
Maintaining headers/cookies along requests during proxy recording

### ISSUE THREAD

**Issue by logicquest** [bbyars/mountebank#380]
#### Expected Behavior
Header information response from API 1 is sent to API 2  request during API Chaining

#### Actual Behavior
Header information response from API 1 is sent to API 2  request during API Chaining

#### Steps to reproduce

- Assuming there are three Apis:
1. Login (Sets user information & api access key as headers)
2.  Critical API (Can be acessed only after Login Api/ with api access key in headers which changes after each login)
3. Logout (Can be acessed only after Login Api/ with api access key in headers which changes after each login)

To record the critical API, the proxy has to retain the headers of API 1's response and pass it to API 2.

**Comment by bbyars** [comment]
Hi there,
I need a little help understanding the issue. While you're recording, the client (e.g. the system under test) is responsible for passing the auth tokens in the header. The proxy will see those and forward them onto API 2 and save the response of API 2. When you're replaying, API 2 will return that response, and if you saved predicates according to the header, will also require the auth tokens. In that use case, it's the client (system under test) that has to retain the headers, not the proxy. Can you explain why the proxy has to change?
