### ISSUE TITLE
Performance improvements with many predicates

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#382]
Reporting on the google group - imposters with several predicates make the imposter unusable for performance testing

**Comment by bbyars** [comment]
I responded to a thread regarding load testing with mountebank when a service has a downstream dependency that requires complex predicates to emulate the services provided by the dependency.  My impression was that complex predicates can severely slow down response times from Mountebank.  Someone suggested using javascript injection to speed up the handling of the request to response match.  I don't think this is a solution (unless I'm missing something) since I would need to code how to match to the request body in Javascript in the same manner predicates have to match.  

Am I off base or missing something?

Here are the CPU loads with 3 instances of mountebank running behind an nginx load balancer on a 4 CPU box with 16 GB RAM.  As you can see, node/Mountebank is eating the CPU while the java service is idling comparatively.

Any suggestions???


Tasks: 133 total,   4 running, 129 sleeping,   0 stopped,   0 zombie
%Cpu(s): 84.5 us,  0.8 sy,  0.0 ni, 14.7 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 15791924 total, 10643204 free,  3123688 used,  2025032 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12207476 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
12105 root      20   0  720652 100228  11052 R 101.7  0.6   4:49.97 node
12133 root      20   0  719176  98488  11056 R 101.3  0.6   4:50.00 node
12072 root      20   0  719252  97924  11056 R 101.0  0.6   4:50.04 node
12581 root      20   0 6885316   1.5g  19024 S  34.6  9.9   3:24.88 java
 1047 root      20   0  832280  93536  25232 S   0.7  0.6   0:23.57 dockerd

**Comment by bbyars** [comment]
They're using xpath to do matching.  

"predicates": [
       {  "and": [
			{
				"equals": {
				   "method": "POST",
				   "path": "/"
			    }
           },
	       {
			    "exists": { "body": true },
			    "xpath": { 
   				    "selector": "//*[local-name() = 'SomeXmlElement']"
	            }
	       },
	       {
                "equals": { "body": "160418" },
                "xpath": { 
                    "selector": "//a:xmlElement1/a:xmlElement2/a:xmlElement3/a:date",
                    "ns": {
                       "a": "http://some-name-space"
                    }
                }
           }
          ]
	}
    ]

I took a simple 2 predicate imposter that I was running at 18 req/sec with a 28ms response time using 36 threads in jmeter and added about 30-40 additional predicates (that I knew would never match).  After adding the no-match predicates, the request rate couldn't get over about 8/sec and the response times went to 4+ seconds.  This was done without docker.


AcesHigh | AcesHigh | Thu, Oct 4, 9:28 AM (2 days ago) |   |  
-- | -- | -- | -- | --
AcesHigh
to mountebank-discuss | to mountebank-discuss
to mountebank-discuss

**Comment by colinschoen** [comment]
We are also running into performance issues using imposters with tons of stubs (500+) and each stub having 3-4 simple predicates (mostly all equals or deepEquals). We are seeing timings around 300ms at 1 TPS on a 16 CPU box with 120GB of ram. The real issue is when the TPS increases (e.g 20 QPS) and requests are getting queued causing them to take upwards of 6+ seconds.

**Comment by bbyars** [comment]
Thanks for the details @colinschoen. I'm pushing to get the current release out, but will include this in the next one.

**Comment by colinschoen** [comment]
Thanks for the response!

**Comment by bbyars** [comment]
No problem - the response is easy. The fix... less so :) I think it'll
require some additional infrastructure for storage and querying.

**Comment by bbyars** [comment]
Left initial solution idea on #279. Feedback welcome.

**Comment by colinschoen** [comment]
Awesome. I'll take a look!
