### ISSUE TITLE
Support overriding Host header with injectHeaders

### ISSUE THREAD

**Issue by colinschoen** [bbyars/mountebank#388]
#### Expected behaviour
Specifying a `Host` header in `injectHeaders` within a proxy includes the overwritten `Host` header in the proxied request.
...

#### Actual behaviour
A specified `Host` header in `injectHeaders` has no bearing on the proxied request and a `Host` header is always set as specified here https://github.com/bbyars/mountebank/blob/master/src/models/http/httpProxy.js#L66
...

#### Steps to reproduce
Create an imposter with the following configuration:
```
{
  "protocol": "http",
  "port": 4545,
  "numberOfRequests": 0,
  "requests": [],
  "stubs": [
    {
      "responses": [
        {
          "proxy": {
            "to": "http://newhost:8000",
            "mode": "proxyAlways",
            "predicateGenerators": [
              {
                "matches": {
                  "path": true
                },
                "caseSensitive": true
              }
            ]
          }
        }
      ]
    }
  ],
  "_links": {
    "self": {
      "href": "http://mb:2525/imposters/4545"
    }
  }
}
```

Observe that all proxied requests do not use the `Host` header specified in `injectHeaders`.
...

#### Software versions used
```
mountebank : 1.15.0
```

**Comment by colinschoen** [comment]
We have a service foo that requires a custom host header value be set in order to return the proper response. We intend to use mountebank as a proxy for traffic to foo in testing.  If `Host: custom host` is set via `injectHeaders` it seems like the expected functionality would be to respect that value and use it in the proxied request. Yes, if a mountebank user incorrectly specifies a `Host` header in `injectHeaders` the downstream service won't know which virtual host to use, but this seems difficult to accidentally configure. Thoughts?

**Comment by colinschoen** [comment]
Hi Brandon,

I just wanted to check and see if you had a chance to review this use case.

**Comment by bbyars** [comment]
Hi Colin,
Yes, I'm comfortable with allowing the injectHeaders host to override the
default proxy host. I have some significant time constraints at the moment,
so your quickest turn-around will be submitting a pull request if you're
interested. I'm happy to point you in the right direction. The offending
code is line 66 in this file:
https://github.com/bbyars/mountebank/blob/master/src/models/http/httpProxy.js
.
-Brandon
