### ISSUE TITLE
How do you change the _proxyResponseTime of the proxied response

### ISSUE THREAD

**Issue by mdfarhanin** [bbyars/mountebank#403]
#### Expected behaviour

Ability to update the proxyResponseTime of the saved proxied response. 

#### Actual behaviour

Unable to change this field

#### Steps to reproduce

Eg)
stubs:
   [
    {
      responses: [
        {
          proxy: {
            to: "https://abc.com",
            mode: "proxyOnce",
            addDecorateBehavior: "(request, response) => {response._proxyResponseTime=5000}",
            predicateGenerators: [{
              matches: {
                path: true,
                headers: {
                    "header1" : true,
                    "header2" : true,                
                  }
                }
            }]
          }
        }
      ]}]

#### Software versions used

OS         : Mac
mountebank : 1.13.0
node.js    : Node.js (6.14.4)
  (only if installed via npm)

**Comment by mdfarhanin** [comment]
Adding the saved imposter for reference

 "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              “header1”: “value1”,
              “header2”: “value2”,
              },
            "body": “……”,
            "_mode": "text",
            "_proxyResponseTime": 279
          },
          "_behaviors": {
            "decorate": "(request, response) => {response._proxyResponseTime=5000}"
          }
        }
      ]

**Comment by bbyars** [comment]
@mdfarhanin Can you give some details on what your ultimate goal is by changing _proxyResponseTime? In the example above, even if the decorate behavior set the field, nothing would change about the response (it's saved primarily to add wait behaviors if needed). Are you trying to set a wait behavior to add latency on the response, or is there some other aim?

**Comment by bbyars** [comment]
Closing based on unknown context (e.g. could update in JSON out of band without mountebank support). LMK if there's a runtime need.
