### ISSUE TITLE
Mailparser2 dependency licensed solely with EUPL

### ISSUE THREAD

**Issue by sbwsg** [bbyars/mountebank#409]
The mailparser package that mountebank employs, [mailparser2](https://www.npmjs.com/package/mailparser2), appears to be a fork of [mailparser](https://github.com/nodemailer/mailparser) but with a more restrictive choice of license.  In particular the `mailparser2` package only allows the source to be distributed under EUPL v1.1 whereas `mailparser` is more permissively dual-licensed with both EUPL 1.1 as well as an MIT license.

Would you accept a PR switching mountebank to the `mailparser` library's latest 2.x version?  I would be happy to make the PR if you are amenable.

**Comment by bbyars** [comment]
Absolutely, thanks for noticing. Looks like I need to add a license scan to
the dependency list to make sure I don't accidentally include a restrictive
license.
-Brandon

**Comment by sbwsg** [comment]
Great, thankyou, I've prepared a branch with a change against mountebank but just noticed that the LICENSE.MIT text was recently corrected in the mailparser & mailsplit libraries that mb depends on. New npm packages with those changes hasn't been published yet so I've [asked the author to cut new versions]( https://github.com/nodemailer/mailparser/issues/212) and will hold on creating a PR against mountebank until that's resolved.

Cheers!
