### ISSUE TITLE
Multiple stubs with identical predicates generated by proxy

### ISSUE THREAD

**Issue by colinschoen** [bbyars/mountebank#426]
#### Expected behaviour
Stubs generated by proxies that lead to identical set of predicates should create one stub with the set of predicates and multiple responses in the order in which the proxy received each request.
...

#### Actual behaviour
Stubs generated by proxies from requests that lead to an identical set of predicates result in multiple stubs being generated. Due to the mountebank always returning the first stub for a request that satisfies all predicates, all stubs other than the first are masked by the first stub. 
...

#### Software versions used
`1.16.0`

**Comment by bbyars** [comment]
@colinschoen Is this in proxyOnce or proxyAlways mode?

**Comment by colinschoen** [comment]
This is in `proxyAlways` mode.

**Comment by bbyars** [comment]
Thanks @colinschoen. There is code already attempting to do this -- see the 'should record new stubs with multiple responses behind proxy resolver in proxyAlways mode' test in [httpProxyStubTest.js](https://github.com/bbyars/mountebank/blob/master/functionalTest/api/http/httpStubTest.js).

Do you have a reproducible example? That test is pretty simple (matching paths), but I'm not sure what it takes to trigger this bug.

**Comment by colinschoen** [comment]
Thanks for the response. Noting I saw this. I'll get a repro example shortly.

**Comment by bbyars** [comment]
I was able to reproduce. Working on it now

**Comment by bbyars** [comment]
@colinschoen Can you see if installing the latest (non-released) version fixes your issue?

````
npm install mountebank-dev@2.2.0-beta.3294
````

Let me know if that was it...

**Comment by colinschoen** [comment]
Sorry for the delay. This looks great:


[ex.txt](https://github.com/bbyars/mountebank/files/3374899/ex.txt)
