### ISSUE TITLE
protofile property required

### ISSUE THREAD

**Issue by bdfinst** [bbyars/mountebank#442]
#### Expected behaviour

Expected the protofile to be an optional property when not defining custom protocols.

#### Actual behaviour

```
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

       5 |   const port = mbConfig.mbApiPort
       6 | 
    >  7 |   return mountebank.create({
         |                     ^
       8 |     port: port,
       9 |     nologfile: true,
      10 |     allowCORS: true,

      at loadCustomProtocols (node_modules/mountebank/src/mountebank.js:102:25)
      at loadProtocols (node_modules/mountebank/src/mountebank.js:134:27)
      at Object.create (node_modules/mountebank/src/mountebank.js:169:21)
      at create (test/mountebank/mbStartServer.js:7:21)
      at Object.it (src/api/team/getTeams.spec.js:11:15)
```

#### Steps to reproduce

Define the server start function

```
import mountebank from 'mountebank'

const mbConfig = {
  mbApiPort: 2525,
  imposterTeamsPort: 8042,
  localhost: 'http://127.0.0.1',
}

export default () => {
  const port = mbConfig.mbApiPort

  return mountebank.create({
    port: port,
    nologfile: true,
    allowCORS: true,
    debug: true,
    logLevel: 'debug',
    // protofile: './protocols.json',
    localOnly: true,
  })
}
```

Then call the function to start the server.

#### Software versions used

```
OS         : OSX 10.14.5
mountebank : 2.1.0
node.js    : 10.15.0
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

The log file is empty when running in debug.

```
Log contents here
```

**Comment by karankural** [comment]
@bdfinst - Is you issue fixed I am facing the same issue!

ERROR : TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined 

Log file : 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle specs@1.0.0~prestart: specs@1.0.0
6 info lifecycle specs@1.0.0~start: specs@1.0.0
7 verbose lifecycle specs@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle specs@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:../JavaScript/mountebank/node_modules/.bin
9 verbose lifecycle specs@1.0.0~start: CWD: /Documents/projects/JavaScript/mountebank
10 silly lifecycle specs@1.0.0~start: Args: [ '-c', 'node src/index.js' ]
11 silly lifecycle specs@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle specs@1.0.0~start: Failed to exec start script
13 verbose stack Error: specs@1.0.0 start: `node src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid specs@1.0.0
15 verbose cwd /Documents/projects/JavaScript/mountebank
16 verbose Darwin 17.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v11.6.0
19 verbose npm  v6.5.0-next.0
20 error code ELIFECYCLE
21 error errno 1
22 error specs@1.0.0 start: `node src/index.js`
22 error Exit status 1
23 error Failed at the specs@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bdfinst** [comment]
No. For now, I'm using a config workaround and configuring a dummy dummy. I was looking into the code to see if I could submit a PR, but I need to finish up some deliverables first before I get back to it.

**Comment by karankural** [comment]
It worked. Thanks
