### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by simhem** [bbyars/mountebank#445]
#### Expected behaviour

Click on add button, should open modal "Add imposter"

![image](https://user-images.githubusercontent.com/10629657/61286326-e771ce00-a7c2-11e9-8912-339cd49c1634.png)

#### Actual behaviour

When clicked on, the button triggers a *TypeError*, that refers to this line (https://github.com/bbyars/mountebank/blob/master/src/public/scripts/imposters.js#L168) and more specifically the object *this*

![image](https://user-images.githubusercontent.com/10629657/61286589-7383f580-a7c3-11e9-96ff-2293383678ca.png)

#### Steps to reproduce

Clean installation of mountebank 2.1.0 on Windows :
- Install nodeJs 10.16 LTS
- install mountebank 2.1.0
- Go to http://localhost:2525/imposters 
- Click on the **+** button

#### Software versions used

```
OS         : Windows (but occurs on RHEL7)
mountebank : 2.1
node.js    :  10.16
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

{"message":"[mb:2525] mountebank v2.1.0 now taking orders - point your browser to http://localhost:2525/ for help","level":"info","timestamp":"2019-07-16T10:08:05.621Z"}
{"message":"[mb:2525] config: {\"options\":{\"loglevel\":\"debug\",\"port\":2525,\"noParse\":false,\"pidfile\":\"mb.pid\",\"nologfile\":false,\"logfile\":\"mb.log\",\"allowInjection\":false,\"localOnly\":false,\"ipWhitelist\":[\"*\"],\"mock\":false,\"debug\":false,\"heroku\":false,\"protofile\":\"protocols.json\"},\"process\":{\"nodeVersion\":\"v10.16.0\",\"architecture\":\"x64\",\"platform\":\"win32\"}}","level":"debug","timestamp":"2019-07-16T10:08:05.624Z"}
{"message":"[mb:2525] GET /images/book.jpg","level":"info","timestamp":"2019-07-16T10:08:07.095Z"}

#### More info

I've noticed that in my situation, when using node 6.11.5 and mountebnak 1.13, i don't get any error.
I am behind a corporate proxy, maybe this could have an impact ?

**Comment by bbyars** [comment]
I've decided to remove the UI functionality as I never intended to support the JQuery implementation. If time allows, I'd like to convert that page to a React app.
