### ISSUE TITLE
It's hard to understand how to implement a custom protocol

### ISSUE THREAD

**Issue by dAnjou** [bbyars/mountebank#453]
I've read the documentation about custom protocols but I still don't understand what the data flows are. Plural because there seem to be two, one when the custom protocol server is bootstrapped and the other one when an actual test request comes in.

A visual add like a sequence diagram would help, I think.

**Comment by dAnjou** [comment]
Figured it out and created really basic an LDAP protocol: https://gitlab.com/dAnjou/mountebank-ldap

Feel free to steal the diagram.

**Comment by bbyars** [comment]
Thank you! I'll take a deeper look this weekend, but at first glance it
looks awesome!
-Brandon

**Comment by bbyars** [comment]
Added the diagram, thanks so much.

**Comment by dAnjou** [comment]
Oh cool, thanks! I hope to find some time for polishing the repo.
