### ISSUE TITLE
resource conflict: Port 60246 is already in use

### ISSUE THREAD

**Issue by ruudk** [bbyars/mountebank#466]
#### Expected behaviour

When starting mountebank with: `mb --mock --configfile mountebank.ejs`
it will create all the imposters defined in the config. But if one of the ports is not available, mb doesn't crash, but just keeps running.

It should immediately stop the program when the port cannot be allocated.

#### Actual behaviour

```
$ mb --mock --configfile mountebank.ejs
info: [mb:2525] mountebank v2.1.0 now taking orders - point your browser to http://localhost:2525/ for help
info: [mb:2525] PUT /imposters
info: [http:60245 Stripe] Open for business...
error: [mb:2525] error creating imposter: {"code":"resource conflict","message":"Port 60246 is already in use","name":"Error","stack":"Error\n    at Object.from (/usr/lib/node_modules/mountebank/src/util/inherit.js:15:17)\n    at createError (/usr/lib/node_modules/mountebank/src/util/errors.js:10:26)\n    at Object.ResourceConflictError (/usr/lib/node_modules/mountebank/src/util/errors.js:21:34)\n    at Domain.error (/usr/lib/node_modules/mountebank/src/models/imposter.js:16:36)\n    at Domain.emit (events.js:182:13)\n    at Domain.EventEmitter.emit (domain.js:441:20)\n    at Server.EventEmitter.emit (domain.js:454:12)\n    at emitErrorNT (net.js:1317:8)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
info: [http:60247 x] Open for business...
```

#### Steps to reproduce

make sure the port is not available when starting mb.

#### Software versions used

```
OS: circleci ubuntu
mountebank: docker andyrbell/mountebank
```

**Comment by jonscottclark** [comment]
@ruudk

> It should immediately stop the program when the port cannot be allocated.

Why should this quit the entire server? We have a use case where getting this error message allows us to retry the API call on a different port. Also, if Mountebank is running as a persistent service, one bad API response should not halt that service to the detriment of other dependencies.

**Comment by ruudk** [comment]
But in this case, I have specified the port number in my config. If MB cannot get that port, it means something else (prob another instance of MB) already took that port. You can wait forever, but chances are high that you'll never get the port.

**Comment by bbyars** [comment]
I agree with @jonscottclark. There are several instance in mountebank's error handling where it makes a best effort and logs the error rather than crashing (invalid JSON, bad injection functions, etc). Immediately stopping on a port conflict would violate that principle.

**Comment by dzotovwork** [comment]
Hello guys, I have the same problem.
{"errors":[{"code":"resource conflict","message":"Port 32015 is already in use"}]}
I am running mountebank 2.4.0 at k8s, and sometimes (rarely) catch this error, when try to create imposters, I can`t select random free port from list in run time. How can I resolve this problem? My ports is in 32000-34000 range

**Comment by bbyars** [comment]
Hi Dmitry,
If you simply don't pass a port in the imposter configuration to
mountebank, mountebank will pick a random free port [1]. If you're making a
POST or PUT call to /imposters to create them, the response will reflect
the captured port back to you, or you can always query the actual ports
used with a call to GET /imposters. That strategy may be the easiest if
you're running into something else competing for your port selection.
-Brandon

[1] Technically, it's up to each protocol to implement that behavior, and
community extensions may not. It does work that way for all the built-in
protocols, though.

**Comment by dzotovwork** [comment]
Oh... If I could set up random port to my app...
This is hardcode and I can`t change this port in my app, that go to mountebank, in runtime :( 
![image](https://user-images.githubusercontent.com/43908260/107179109-bb422180-69e6-11eb-9efd-f9c225eac9a8.png)
