### ISSUE TITLE
[bug] add imposter on ui

### ISSUE THREAD

**Issue by pinghe** [bbyars/mountebank#468]
v2.1.1

yarn global add mountebank

http://localhost:42525/imposters#  add is error

![image](https://user-images.githubusercontent.com/377955/66796568-a496d200-ef3a-11e9-910b-456c730eb8e5.png)

![image](https://user-images.githubusercontent.com/377955/66796637-df006f00-ef3a-11e9-9182-508c432f8c21.png)

**Comment by ashokgowtham** [comment]
The js code uses arrow functions and also makes use of `$(this)` to refer to the event target, which doesn't work as intended.
arrow function should not be used for event handler methods like it is used here.
Arrow functions reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by bbyars** [comment]
Thanks for this. I'm removing the jquery implementation as it was never robust. If time allows in the future I'll turn that page into a react app with more functionality.
