### ISSUE TITLE
Can't npm install montebank due to snyk when behind firewall blocking github public access

### ISSUE THREAD

**Issue by shusak** [bbyars/mountebank#470]
#### Expected behaviour
Should be able to install montebank in a locked down build system. 
...

#### Actual behaviour
Our system is locked down from accessing the internet. We use Artifactory as our registry, however, it looks like there is a step in the `npm install` of montebank (or one of its dependencies) that causes snyk to reach out to public github, which is not something we can do from our build machines.
...

#### Steps to reproduce
Block github access.
npm install montebank

Get error:
 
```
16:17:56 + npm install
16:58:33 npm ERR! Error while executing:
16:58:33 npm ERR! /usr/bin/git ls-remote -h -t git://github.com/snyk/node-https-proxy-agent.git
16:58:33 npm ERR! 
16:58:33 npm ERR! undefined
16:58:33 npm ERR! exited with error code: 128
```
...

#### Software versions used

```
OS         :  Jenkins
mountebank : latest
node.js    : 10.16.3
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```

**Comment by bbyars** [comment]
Fixed with 2.1.2
