### ISSUE TITLE
For HTTP recordings at least, consider support Servirtium's markdown format (optionally)

### ISSUE THREAD

**Issue by paul-hammant** [bbyars/mountebank#486]
Ref: https://github.com/servirtium/README

Not to take away from Mountebank's excellent APIs, but support of Servirtium's markdown format could be good too :)

**Comment by bbyars** [comment]
I totally agree.

For now, the best option is a CLI converter than can convert Servirtium's markdown format to something that can be passed to the --configfile CLI option (see http://www.mbtest.org/docs/commandLine#config-file). Right now, that means an EJS template, or simply inlining everything directly into JSON. Optionally, the CLI converter could take the reverse transformation too -- converting a JSON output from mountebank and saving it in Servirtium markdown.

**Comment by bbyars** [comment]
@paul-hammant Good news. The 2.4.0 release supports custom formatters, which allow anyone to create a formatter that can convert to and from Servirtium format. Docs available at http://www.mbtest.org/docs/commandLine#custom-formatters
