### ISSUE TITLE
Data is altered if i try to send it via proxy imposter

### ISSUE THREAD

**Issue by Priya1ux** [bbyars/mountebank#510]
#### Expected behaviour

Raw data is sent to MB imposter (eg: -t 1000 "string")
Data should not be altered.
#### Actual behaviour
Data is altered. if without "-t" , no issue ..when we use "-t" this issue is seen.

#### Steps to reproduce

...

#### Software versions used
mountebank v2.1.2

Installation method : npm
  
```

#### Log contents in mb.log when running mb --loglevel debug

<!--
Please review before pasting to ensure no sensitive data is copied
-->

```
Log contents here
```

**Comment by bbyars** [comment]
Hi there,
Can you clarify what the "-t" refers to? And the workflow? Is it an HTTP
imposter proxying to a downstream server?

**Comment by Priya1ux** [comment]
Below MB imposter is used:
{
  "protocol": "tcp",
  "port": 3000,
  "stubs": [{
    "responses": [{
      "proxy": {
        "to": "tcp://127.0.0.1:6666",
        "mode": "proxyAlways"
      }
    }]
  }]
}

Input packet which is sent to mountebank is not same as the output packet from MB.

**Comment by bbyars** [comment]
Hi there,
Are you proxying to a binary server? If so, the proxy imposter needs "mode" set to "binary":

````
{
    "protocol": "tcp",
    "port": 3000,
    "mode": "binary",
    "stubs": [{
        "responses": [{
            "proxy": {
                "to": "tcp://127.0.0.1:6666",
                "mode": "proxyAlways"
            }
        }]
    }]
}
````

I'm closing for now as it seems likely that is the issue. Let me know if that still doesn't work, but I will need some information about the service you're proxying to in order to continue troubleshooting.
