### ISSUE TITLE
Question: about sidecar behavior for a mock

### ISSUE THREAD

**Issue by osukaa** [bbyars/mountebank#553]
Hello,

I have a question about how to work with mountebank when there's a sidecar in the middle. When running my application (subject under test) to access its upstream dependencies, it needs to go through a specific address `dependency.xyz.com` (for example), that address points to an envoy sidecar which knows how to reach a given `dependency.`

My question is that I want upon registering an imposter, to then mountebank register itself with the sidecar such that is available for my subject under test to request. Is there a way to achieve this?

I was going through the documentation but couldn't find something similar.

**Comment by bbyars** [comment]
There's nothing specifically for sidecar registration. I wonder if setting
the http_proxy (or https_proxy) environment variables would work? They're
respected for proxy operations <http://www.mbtest.org/docs/api/proxies>.
-Brandon

**Comment by osukaa** [comment]
Thank you! Will try that
