### ISSUE TITLE
How to use --datadir option efficiently

### ISSUE THREAD

**Issue by shekharsxn35** [bbyars/mountebank#554]
Its not an issue but just wanted to ask how can use --datadir option for scalability as will have to use for performance testing also mountebank document is not clear and did not find any example of using this mb command with --datadir option

I am using following option but can not see mbdb directory on my local. Also Can we give our custom options like following

--datadir /opt/.mbdb

**mb --configfile /Users/abcd/imposters.json --debug --loglevel=debug --datadir .mbdb**

**Comment by bbyars** [comment]
You're using it correctly (but not the --loglevel, you need to replace the
= character with a space for shell processing). The dot prefix on the
filename makes it a hidden directory, so you need to use something like "ls
-al" to see it on the terminal, and it will probably be hidden on your
graphical file explorer. Simply remove the dot if you'd like to make it
more visible, and yes, you can change the directory to whatever you want.
The command below unhides the file, puts it in /opt, and fixes the loglevel.

*mb --configfile /Users/abcd/imposters.json --debug --loglevel debug
--datadir /opt/mbdb*

**Comment by shekharsxn35** [comment]
I have used the same but could not be able to generate it 
mb --configfile /Users/abcd/imposters.json --debug --loglevel debug --datadir /opt/mbdb

Still giving this error "ls /opt/mbdb"
ls: /opt/mbdb: No such file or directory

**Comment by bbyars** [comment]
Can you send the logs that show the error? (Please sanitize first if
there's anything sensitive in them)

**Comment by shekharsxn35** [comment]
Please find the mb.log
[mb.log](https://github.com/bbyars/mountebank/files/4665501/mb.log)

**Comment by shekharsxn35** [comment]
Thanks a lot. It is working fine. I was looking in the wrong directory.

**Comment by bbyars** [comment]
Perfect, thanks for letting me know.
