### ISSUE TITLE
Security Scan

### ISSUE THREAD

**Issue by Harman9797** [bbyars/mountebank#555]
This is surely too much to ask but we ran a veracode analysis on mountebank and came across these security risks:
Very high:  1 -- OS Command Injection 1
High: 27 -- Cross-Site Scripting 15, Directory Traversal 12

Instances locations
Very high: mountebank/.../protocols.js 70
High: /.../models/http/baseHttpServer.js 111
         /.../models/http/baseHttpServer.js 133
        /.../imposterController.js 46
        /.../imposterController.js 75
        /.../imposterController.js 102
        /.../imposterController.js 158
        /.../imposterController.js 176
        /.../imposterController.js 321
        /.../models/imposterPrinter.js 70
        /.../models/imposterPrinter.js 71
       /.../imposterController.js 141
       /.../src/models/mbConnection.js 64
       /mountebank/.../tcp/tcpServer.js 80
       /mountebank/.../tcp/tcpServer.js 108
       /.../scripts/urlHashHandler.js 18
and 
      /.../controllers/feedController.js 50
      /.../controllers/feedController.js 89
      .../filesystemBackedImpostersRepository.js 118
      .../filesystemBackedImpostersRepository.js 137
      .../filesystemBackedImpostersRepository.js 168
      .../filesystemBackedImpostersRepository.js 295
      /.../controllers/logsController.js 22
      /mountebank/.../src/mountebank.js 108
      /mountebank/.../src/mountebank.js 185

Could there be a solution or support to tackle these, may be in future releases.

**Comment by brunns** [comment]
Are there any open source tools which provide a similar analysis, which could be included in the build pipeline? There's probably not enough detail in this report to fix much.

**Comment by bbyars** [comment]
Thanks for sending. I'll take a look in more depth, but suspect there's not
a lot to be done. I looked at the "Very High" risk, for example, and it's
the code that passes context to a custom protocol implementation. It's
doing exactly what it should -- passing along the context on the command
line -- and stringifies it as JSON for the protocol implementation to
parse. Similarly I sampled a couple of the Highs around directory
traversal. Veracode appears to be flagging writes to the filesystem for
mountebank's persistent storage. By default, everything is in memory, but
if you want more scale (and you have to explicitly pass the --datadir flag
to mountebank to enable that), then mountebank will need to write to the
filesystem.

I welcome suggestions if I've simply misunderstood the concern, but the
ones I sampled appear to be false positives to me.
-Brandon

**Comment by bbyars** [comment]
Closing as it's unclear there's anything actionable; items reviewed are needed functionality and under configuration switches.
