### ISSUE TITLE
Use files instead of JSON

### ISSUE THREAD

**Issue by Unit111** [bbyars/mountebank#569]
My problem is the following: I have a docker-compose setup where one of the services is the test project and another one is the SUT where Mountebank is running. In my currect setup I load the imposters from a file on the Test container and send them as JSON to the SUT container. The problem is that some of them have 200+k lines which introduces a big delay when reading, parsing and sending them. Is there a way to tell Mountebank over the API to use files (same json files are accessible on the SUT container) instead of JSON?

**Comment by brunns** [comment]
Does the --configfile command line option help? See
http://www.mbtest.org/docs/commandLine

**Comment by Unit111** [comment]
Thank you for the quick response. Unfortunately the command line does not help in this case. I am looking for something I can execute from a different container. If I had access to be shell of the container Mountebank is running on it would be very easy to achieve my goal- I can curl to localhost and set wathever I want. But I have to do this from one alpine container to another (and using Docker in Docker is not an option because of permission issues).

**Comment by bbyars** [comment]
I might be oversimplifying, but from your description it sounds quite easy
to create a wrapper script that initializes the mountebank container and
then uses the API to send the JSON inside the files. Any delay you
incur reading those files would be the same regardless of whether
mountebank does it or your wrapper script does it, no?

The other option would be to use the --datadir flag. Once mountebank is
initialized with the configuration the first time (possible through a
wrapper script, or --configfile), then as long as it has access to the same
volume, it will reload the configuration much faster, as it doesn't try and
maintain everything in memory.
-Brandon

**Comment by Unit111** [comment]
I did something similar to the above suggestion- implemented a small Flask app with a single endpoint changing the stubs. Then I exposed the port of the app and connected to it from the other container passing the file names.
I think this discussion is ready to be closed.
