### ISSUE TITLE
Mountebank does not return value fetched from MySQL database through response.body in decorated behaviour

### ISSUE THREAD

**Issue by Praveen-sekar** [bbyars/mountebank#587]
**Sample Imposter Created** 

{
  "port": 9080,
  "protocol": "http",
  "stubs": [
    {
      "responses": [
        {
          "is": {
            "body": "{'sessioncount':'${uuid}'}"
          },
          "behaviors": [
            { "decorate": "function (request, response) {let mysql = require('mysql'); const connection = mysql.createConnection({ host: 'localhost', user: 'root', password: 'c0mcast!', database: 'my_sql', connectTimeout: 100000 }); function sample(){ connection.query('SELECT count(*) as Count FROM sample', function (err, result, fields) { resp=result[0].Count;response.body=response.body.replace('${uuid}', resp);});} sample();}" }
          ]
        }
      ]
    }
  ]
}

#### Expected behaviour
**Response** : {'sessioncount':'1}'}
...

#### Actual behaviour
**Response** : {'sessioncount':'${uuid}'}
...

#### Steps to reproduce - Actual Issue
response.body.replace code is not working inside connection.query function where actual value to be replaced is being fetched from MySQL . I have noticed the connection being established at MySQL server end from my mountebank server.

...

#### Software versions used

```
OS         : Windows 10
mountebank : 2.3.3
node.js    : v14.15.1
  (only if installed via npm)
Installation method : zip
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```
debug: [http:9080] ::1:1408 => {"requestFrom":"::1:1408","method":"GET","path":"/","query":{},"headers":{"Host":"localhost:9080","Connection":"keep-alive","Cache-Control":"no-cache","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","Postman-Token":"2f8f25b0-8aae-d7bf-f37c-fe5619248619","Accept":"*/*","Sec-Fetch-Site":"none","Sec-Fetch-Mode":"cors","Sec-Fetch-Dest":"empty","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.9"},"body":"","ip":"::1"}
debug: [http:9080] using predicate match: {}
debug: [http:9080] generating response from {"is":{"body":"{'sessioncount':'${uuid}'}"},"behaviors":[{"decorate":"function (request, response) {let mysql = require('mysql'); const connection = mysql.createConnection({ host: 'localhost', user: 'root', password: 'c0mcast!', database: 'my_sql', connectTimeout: 100000 }); function sample(){ connection.query('SELECT count(*) as Count FROM sample', function (err, result, fields) { resp=result[0].Count;response.body=response.body.replace('${uuid}', resp);});} sample();}"}]}
debug: [http:9080] using stub response behavior [{"decorate":"function (request, response) {let mysql = require('mysql'); const connection = mysql.createConnection({ host: 'localhost', user: 'root', password: 'c0mcast!', database: 'my_sql', connectTimeout: 100000 }); function sample(){ connection.query('SELECT count(*) as Count FROM sample', function (err, result, fields) { resp=result[0].Count;response.body=response.body.replace('${uuid}', resp);});} sample();}"}]
debug: [http:9080] ::1:1408 <= {"statusCode":200,"headers":{"Connection":"close"},"body":"{'sessioncount':'${uuid}'}","_mode":"text"}
debug: [http:9080] ::1:1408 CLOSED
debug: [http:9080] ::1:1431 ESTABLISHED
info: [http:9080] ::1:1431 => GET /
debug: [http:9080] ::1:1431 => {"requestFrom":"::1:1431","method":"GET","path":"/","query":{},"headers":{"Host":"localhost:9080","Connection":"keep-alive","Cache-Control":"no-cache","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","Postman-Token":"64640181-c698-a6bd-dd35-5519b78b51d5","Accept":"*/*","Sec-Fetch-Site":"none","Sec-Fetch-Mode":"cors","Sec-Fetch-Dest":"empty","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.9"},"body":"","ip":"::1"}
debug: [http:9080] using predicate match: {}
debug: [http:9080] generating response from {"is":{"body":"{'sessioncount':'${uuid}'}"},"behaviors":[{"decorate":"function (request, response) {let mysql = require('mysql'); const connection = mysql.createConnection({ host: 'localhost', user: 'root', password: 'c0mcast!', database: 'my_sql', connectTimeout: 100000 }); function sample(){ connection.query('SELECT count(*) as Count FROM sample', function (err, result, fields) { resp=result[0].Count;response.body=response.body.replace('${uuid}', resp);});} sample();}"}]}
debug: [http:9080] using stub response behavior [{"decorate":"function (request, response) {let mysql = require('mysql'); const connection = mysql.createConnection({ host: 'localhost', user: 'root', password: 'c0mcast!', database: 'my_sql', connectTimeout: 100000 }); function sample(){ connection.query('SELECT count(*) as Count FROM sample', function (err, result, fields) { resp=result[0].Count;response.body=response.body.replace('${uuid}', resp);});} sample();}"}]
debug: [http:9080] ::1:1431 <= {"statusCode":200,"headers":{"Connection":"close"},"body":"{'sessioncount':'${uuid}'}","_mode":"text"}
debug: [http:9080] ::1:1431 CLOSED

**Comment by bbyars** [comment]
Unfortunately, the decorate behavior does not support asynchronous
responses like response injection does. The mysql code is asynchronous (it
passes a function callback), so the decorator will have already returned to
mountebank by the time the database response is captured. Switching to response
injection <http://www.mbtest.org/docs/api/injection> and using the callback
parameter should do the trick.
-Brandon
