### ISSUE TITLE
Support SOAP protocol

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#59]

**Comment by uchagani** [comment]
+1 would love to see this feature.  Is there an ETA for it?

**Comment by bbyars** [comment]
Not at the moment.  I started an implementation based on a user request, and then we discovered that their use case would be best served by using the http protocol (which supports soap already) as they had no need to avoid entering the envelope, etc.  Do you have a use case in mind?

**Comment by uchagani** [comment]
@bbyars we have a bunch of soap services i'd like to test with mountebank.  All of them are wsdl based and we normally test by selecting an operation and passing the payload in as the body.  Right now we are testing them using Savon(http://savonrb.com/) but it would be awesome to implement the dependencies in mountebank.

**Comment by bgilner** [comment]
+1 we would like to not only test services but replay recorded/cached responses in some cases when services temporarily go down

**Comment by bbyars** [comment]
Hi there
You can actually record/replay SOAP responses today using the http (or
https) protocol. SOAP adds quite a bit to the body with the envelope, but
in the end it's just XML in the body field and maybe an extra header. You
can set predicates on the path and, if needed, xpath predicates
<http://www.mbtest.org/docs/api/xpath> (or predicateGenerators
<http://www.mbtest.org/docs/api/proxies> if you're recording) to give
different responses for different requests.

Let me know if there's something you don't think you can do today with
mountebank regarding SOAP, or if you need help setting it up.
-Brandon

**Comment by bbyars** [comment]
Closed as can be community supported through protocol extension
