### ISSUE TITLE
Please support the HTTP CONNECT method 

### ISSUE THREAD

**Issue by mikeschinkel** [bbyars/mountebank#600]
#### Problem Statement

[Evidently when an application knows that it is using a proxy](https://stackoverflow.com/a/40329026/102699)  it is supposed to send an [HTTP CONNECT request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) to ask the proxy to open up a tunnel to the proxied resource to pass the TLS encrypted data stream to the proxied server.

In our specific use-case when the builtin `net/http` package in GoLang [is configured to use a proxy](http://blog.ralch.com/articles/network-programming-and-proxies-in-golang/) it will send a `CONNECT` request instead of a `GET` request. The proxy should then set up an HTTP tunnel to exchange the TLS encrypted data stream between the calling client and the upstream proxied server.

However, currently when Mountebank receives a `GET / CONNECT HTTP/1.1` request it just closes the connection without processing it which is exactly what the Node docs says will happen [when the `CONNECT` method is not handled](https://nodejs.org/docs/latest-v14.x/api/http.html#http_event_connect).

For our use-case we cannot `GET localhost` directly because we are using the defacto-standard [GitHub API package for Go](https://github.com/google/go-github) developed by Google and it hardcodes calls to `api.github.com` thus not allowing up to replace the host during testing.

#### Expected behaviour
When an HTTPS client sends a CONNECT request then Mountebank should open an HTTP tunnel and establish a TLS connection.

#### Actual behaviour
When an HTTPS client sends a CONNECT request then Mountebank simply disconnects, as per the Node docs for
[unhandled CONNECT requests](https://nodejs.org/docs/latest-v14.x/api/http.html#http_event_connect).

#### Steps to reproduce
Here in a [Gist](https://gist.github.com/mikeschinkel/9dfaa0efbd0dbdefee221ff48d0ad2f3) is a simple, self-contained Go app and the needed files to reproduce the problem _(`proxy-server.go`, `go.mod`, and `go.sum`.)_

You will need to [**create a GitHub personal auth token**](https://github.com/settings/tokens) and [update your copy of `proxy-server.go`](https://gist.github.com/mikeschinkel/9dfaa0efbd0dbdefee221ff48d0ad2f3#file-proxy-client-go-L16) to use it.

To compile and run in Go [you will need](https://golang.org/doc/install) a version of Go installed and then run this command to test without proxying to Mountebank to ensure it is configured correctly and can talk to GitHub _(I used Go `v1.15` but I think most any recent version should work.):_

```
go run proxy-client
```

The above should output the `README.md` for Mountebank and output to your terminal window if it worked correctly.

Next you need to run Montebank with `--loglevel debug` and `--configfile mb.json` using the `mb.json` file [found in the Gist](https://gist.github.com/mikeschinkel/9dfaa0efbd0dbdefee221ff48d0ad2f3#file-mb-json) after which you can call `proxy-client` again, but this time setting a proxy port of `9999` since the `mb.json` defines an imposter for that port:
```
go run proxy-client -proxy=9999
```
After running the above you will see that Mountebank logs the following to the terminal window in which it is running showing that it accepted the connection then immediately terminated it:

```
debug: [https:9999 testing] ::1:58787 ESTABLISHED 
debug: [https:9999 testing] ::1:58787 CLOSED
```

#### Software versions used

```
OS             : macOS 10.15.7 Catalina 
mountebank     : 2.4.0
node.js        : 7.5.6
Install method : npm
GoLang         : 1.15
```

#### Log contents in mb.log when running mb --loglevel debug

First it outputs this:
```
info: [mb:2525] mountebank v2.4.0 now taking orders - point your browser to http://localhost:2525/ for help
debug: [mb:2525] config: {...}
info: [mb:2525] PUT /imposters
debug: [mb:2525] ::ffff:127.0.0.1:50911 => {...}
info: [https:9999 testing] Open for business...
```

Then I run `go run proxy-client -proxy=9999` and Mountebank immediately outputs:

```
debug: [https:9999 testing] ::1:51263 ESTABLISHED
debug: [https:9999 testing] ::1:51263 CLOSED
```
And #justfyi the Go app will output this and then terminate:
:
```
Get "https://api.github.com/repos/bbyars/mountebank/contents/README.md?ref=master": unexpected EOF
exit status 1
```

**Comment by jbolda** [comment]
We put up a [reproduction](https://github.com/jbolda/mountebank-proxy-to-github) with a `patch-package` diff that allows for easier testing and shows the possible solution. The diff is below. If the maintainers are open to a PR, I can open one with this diff and include tests.

```
diff --git a/node_modules/mountebank/src/models/http/baseHttpServer.js b/node_modules/mountebank/src/models/http/baseHttpServer.js
index 5989672..c5a8a37 100644
--- a/node_modules/mountebank/src/models/http/baseHttpServer.js
+++ b/node_modules/mountebank/src/models/http/baseHttpServer.js
@@ -1,4 +1,5 @@
 'use strict';
+const net = require('net')
 
 /**
  * The base implementation of http/s servers
@@ -76,6 +77,27 @@ module.exports = function (createBaseServer) {
         // Allow long wait behaviors
         server.timeout = 0;
 
+        server.on('connect', (response, client, head) => {
+            const host = response.socket.servername
+            const port = response.socket.localPort
+            const server = net.createConnection({host, port}, () => {
+                client.on('error', err => {
+                    // 'ECONNRESET' IS no-op?
+                    // this seems to be an error we don't need to consider
+                    if (err.code !== 'ECONNRESET') {
+                        console.log('CLIENT TO PROXY ERROR');
+                        console.log(err);
+                    }
+                });
+        
+                console.log('PROXY TO SERVER SET UP TO %s ON %s', host, port);
+                client.write('HTTP/1.1 200 Connection established\r\n\r\n')
+                client.pipe(server)
+                server.write(head)
+                server.pipe(client)
+            })
+        });
+
         server.on('connection', socket => {
             const helpers = require('../../util/helpers'),
                 name = helpers.socketName(socket);
```

**Comment by bbyars** [comment]
Thanks! Absolutely open to a PR.
