### ISSUE TITLE
Proposal: JavaScript API for the ability to run mocker on existing server endpoint

### ISSUE THREAD

**Issue by SuperOleg39** [bbyars/mountebank#610]
## Motivation

Current JS / CLI `mountebank` API immediately create and start new http server.
It means, if we want to test one NodeJS micro-service, we need to create and deploy two containers - one with our service, and one with `mountebank`.
If we have a k8s infrastructure, many applications, and dynamic deployed stands with automated testing, just one additional container with `mountebank` for every application complicates deployment and take many k8s resources.

But what if we can create `mountebank` instance on existing NodeJS application, at new endpoint?

Our micro-service can on demand run integration with `mountebank`, where we create new `express` endpoint, `/mountebank` for example, and pass `req` and `res` objects to special `mountebank` JS API.
After, this micro-service can replace http requests base URL to mocked API to `http://localhost:3000/mountebank`.

For SSR NodeJS applications, on client-side, will be available a relative URL `/mountebank` (nuances with a gateway proxy are possible).

## API overview

Few examples, how new API may looks like

### Nested express.js routers

Inspired by [this reciepe](https://gist.github.com/zcaceres/f38b208a492e4dcd45f487638eff716c)

```js
const express = require('express')
const { createRouter } = require('mountebank')

const app = express();

const mountebankRouter = await createRouter(options)

app.use('/mountebank/*', mountebankRouter)
```

### express.js middeware

```js
const express = require('express')
const { createMiddleware } = require('mountebank')

const app = express();

const mountebankMiddleware = await createMiddleware(options)

app.use('/mountebank/*', mountebankMiddleware)
```

### express.js application

Example for clean `http` NodeJS server

```js
const http = require('http')
const { createApp } = require('mountebank')

const mountebankApp = await createApp(options)

const server = createServer((req, res) => {
  if (req.url.startsWith('/mountebank')) {
    mountebankApp(req, res);
  }
});

server.listen(port);
```

## Implementation

If this feature is discussible, and don't break some `mountebank` core concepts, i can start from a simple demo branch, for this proposal.

**Comment by dzotovwork** [comment]
Awesome proposal !!!! 👍

**Comment by vchuchkalov** [comment]
Hi @bbyars. What do you say?

**Comment by bbyars** [comment]
I'm comfortable with the suggestion. It's close to being possible now (look
at the commented out lines starting at line 39
<https://github.com/bbyars/mountebank/blob/master/mbTest/perf/databaseConcurrencyTest.js>).
It might involve moving some CLI option defaults from the current cli.js
into mountebank.js to avoid having to pass defaults that mountebank expects
(as shown in the link), adding an option to adjust the root path, and
avoiding the socket bind, but looks reasonably straightforward.

**Comment by SuperOleg39** [comment]
Thank you for the recommendations!

Will start working on this soon)

**Comment by SuperOleg39** [comment]
@bbyars , hi!

Create PR, but not sure about all changes:
- `defaults` implementation seems to be unfortunate
- `listenServer` method may be unnecessary

Will waiting review)

**Comment by SuperOleg39** [comment]
Need to create some `publicPath` option for static assets and links on `mountebank` web interface, because current relative path always see to current domain.
I think, will be better to create another PR)
