### ISSUE TITLE
Website Docker Run Command Out Of Date

### ISSUE THREAD

**Issue by tparikka** [bbyars/mountebank#615]
#### Expected behaviour
The docker example at http://www.mbtest.org/docs/install should work.

#### Actual behaviour
The correct run command seems to be `docker run --rm -p 2525:2525 -p 8080:8080 bbyars/mountebank:2.4.0 start --configfile imposters.ejs` and not `docker run --rm -p 2525:2525 -p 8080:8080 mountebank:2.4.0 mb start --configfile imposters.ejs`.

**Comment by erakli** [comment]
I am also cannot find where to fix this one. @bbyars, could you point to the place where is this doc? There [are no "install.ejs" view](https://github.com/bbyars/mountebank/tree/master/src/views/docs)

**Comment by bbyars** [comment]
Thanks both. While it's not released, I've removed the install page from
the next version, deprecating the old operating system installs. Instead of
documenting on instal.ejs, the Docker command will likely need to be added
to the getting started page.
