### ISSUE TITLE
Response Injection: Request body expected in JSON but received in text

### ISSUE THREAD

**Issue by GustavePate** [bbyars/mountebank#62]
Hi,

I'm extending the response injection exemple found in the documentation:
http://www.mbtest.org/docs/api/injection
(in the "response injection" chapter)

What I'm trying is to inject a little of functional logic in my mock.

I should:
1. read the request body
2. compute some of it's values
3. serve a response accordingly

My request body is a json string. My app send data to the mock using:

    unirest.post(full_url)
            .header('Accept', 'application/json')
            .send({'str': text})

What I received in my mountebank script is a string:

    str=message2

where I expected json.

For analysis:

- I use EJS templates (same structure than in http://www.mbtest.org/docs/commandLine)
- I launch mountbank from the commandline with this parameters:

   ./node_modules/.bin/mb --configfile ./test/lib/mountebank/imposters.ejs --allowInjection --port 2526

- Below is the code of my mock.

Thanks for your time and for this usefull tool !

    function (request, state, logger, callback) {

        if (request.isDryRun) {
            callback({});
        }

        logger.info('ADVANCED MOCK MARK I');
        state.requests = state.requests || 0;
        state.requests += 1;

        var reqsize=1;
        var note="mbdefault";
        var req_status = 200;

        if (request.body){
            logger.info("request", request);
            logger.info("state", state);
            logger.info("body", request.body);
            var req = request.body.replace("str=","");

            if (req === "404"){
                req_status=404;
            }
            reqsize = req.length;
            note = "test";

            if (reqsize < 10){
                note="small";
            }else{
                note="big";
            }
        }

        return {
        headers: {
            "content-type": "application/json",
            "content-length": "44",
            "server": "Werkzeug/0.9.6 Python/3.4.0",
            "date": "Tue, 07 Apr 2015 15:01:57 GMT",
            "connection": "close"
        },
        statusCode: req_status,
        body: JSON.stringify({
            nb_char: reqsize,
            weight: note,
            state: state.requests
        }),
        _mode: "text"
        };
    }

**Comment by bbyars** [comment]
Hi Gustave,
It looks like unirest uses a default content type of
application/x-www-form-urlencoded, which will send the key=value format
that you're seeing.  I believe if you add a 'Content-Type' header of
'application/json' you'll get what you want (I suspect you may have been
trying to do that with the Accept header since you set it explicitly, but
Content-Type is what you want).

unirest.post(full_url)
        .header('*Content-Type*', 'application/json')
        .send({'str': text})

Let me know if that doesn't fix it and I'll play with it some more.
-Brandon

**Comment by GustavePate** [comment]
Hi Brandon,

You rock ! you exactly pinpointed  the problem. Everything works now.
Sorry for having made you debug my own code.

And thanks for the quick reply  !

**Comment by bbyars** [comment]
Not a problem at all - glad it's working.
-Brandon
