### ISSUE TITLE
Issue with Injection in Predicate

### ISSUE THREAD

**Issue by anu0123** [bbyars/mountebank#63]
Hi

I am unable to inject any Javascript function inside the predicates of one of the stub.
In the request i have asked to match the Query under PredicateGenerators.

The function which i have written is very simple
 "predicates": [
            {    
             {  "deepEquals":
             {
            "query":
                {"inject": "function(logger)
                {logger.info('Inside injection';)}"
           }}}
           }
I am not able to see any information on logs.
I have allowed Injection on mountebank startup by 
mb --allowInjection.

Can anyone suggest anything ? Or if any changes has to be made ?

**Comment by bbyars** [comment]
Hi there,
The inject predicate looks unlike the other predicates because it needs
access to the entire request and therefore has to be at the top level.
Your example would need to look something like this:

"predicates": [
  {
    "inject": "function(request, logger) { logger.info('Inside injection');
logger.info(JSON.stringify(request, null, 4)); }"
  }
]

The second log statement will show you what the request looks like, and you
can use that to do whatever tests you need.  Let me know if that's still
confusing, happy to help you sort it out.
-Brandon

**Comment by Anushkasharma** [comment]
I am injecting this function in a response which is captured after loading a request onto MounteBank but still it doesn't work.
I had one other question too. Which all predicates can we use besides matches in PredicateGenerators?  Any other used with proper syntax throws errors.
Ex I am using : {
    "port": 7575,
    "protocol": "http",
    "stubs": [
        {
            "responses": [
                {
                    "proxy": {
                        "to": "http://www.orgin-server",
                        "mode": "proxyOnce",
                        "predicateGenerators": [
                            {
                                "or": [
                                    {
                                        "matches": {
                                            "query": true
                                        }
                                    },
                                    {
                                        "contains": {
                                            "query": "lp"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

**Comment by anu0123** [comment]
I am injecting this function in a response which is captured after loading a request onto MounteBank but still it doesn't work.
I had one other question too. Which all predicates can we use besides matches in PredicateGenerators?  Any other used with proper syntax throws errors.
Ex I am using : {
    "port": 7575,
    "protocol": "http",
    "stubs": [
        {
            "responses": [
                {
                    "proxy": {
                        "to": "http://www.orgin-server",
                        "mode": "proxyOnce",
                        "predicateGenerators": [
                            {
                                "or": [
                                    {
                                        "matches": {
                                            "query": true
                                        }
                                    },
                                    {
                                        "contains": {
                                            "query": "lp"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

**Comment by bbyars** [comment]
Hi there,
Responses inline:

I am injecting this function in a response which is captured after loading
> a request onto MounteBank but still it doesn't work.
>

Sorry you're having trouble.  Can you send the full imposter JSON you're
sending so I can troubleshoot?

I had one other question too. Which all predicates can we use besides
> matches in PredicateGenerators? Any other used with proper syntax throws
> errors.
>

The predicateGenerators objects only accept matches.  You can augment them
with caseSensitive and except, but you can't use them to create a contains
predicate, for example.

**Comment by RoyalGunjan007** [comment]
Is there a way to read response file inside decorate and modify it as per use?

**Comment by bbyars** [comment]
Yes. The decorate behavior
<http://www.mbtest.org/docs/api/behaviors#behavior-decorate> accepts both
the request and response as parameters. You can return the modified
response from the function. See the linked to page for examples.
-Brandon
