### ISSUE TITLE
`Dockerfile` manifest should make use of `ENTRYPOINT["mb"]` instead

### ISSUE THREAD

**Issue by x80486** [bbyars/mountebank#671]
While trying `Mountbank` via `Docker`, I believe the manifest should make use of `ENTRYPOINT` instead of `CMD["mb"]`; e.g.: `ENTRYPOINT["mb"]`.

**Comment by bbyars** [comment]
Can you share a bit more detail? What would that solve/prevent?

**Comment by x80486** [comment]
In short, `CMD` defines default commands and/or parameters for a container. In my experience, I use `CMD` to default command(s) which users can easily override. In a different situation, `ENTRYPOINT` is used when defining a specific executable for a container.

Since `mb` is a must, then `ENTRYPOINT` makes more sense, and users, if desired, can pass more parameters to it.

**Comment by bbyars** [comment]
Make sense, thanks.
