### ISSUE TITLE
API contract missing ignore field from predicate generators.

### ISSUE THREAD

**Issue by brunns** [bbyars/mountebank#679]
#### Expected behaviour

[API contracts](http://www.mbtest.org/docs/api/contracts) should include ['ignore' field](http://www.mbtest.org/docs/api/proxies#proxy-predicate-generators), as added in version [2.6.0](http://www.mbtest.org/releases/v2.6.0).

#### Actual behaviour

`ignore` field not shown.

#### Steps to reproduce

Visit [API contracts](http://www.mbtest.org/docs/api/contracts) page

**Comment by bbyars** [comment]
Thanks for reporting!
