### ISSUE TITLE
Can mb run in background?

### ISSUE THREAD

**Issue by itrufeng** [bbyars/mountebank#69]
I have a shell

```
rake start
curl -i http://localhost:2525
```

But mb run in foreground. the curl can't called.
Thanks.

**Comment by bbyars** [comment]
Hi there,
You can use your shell to do this for you, something like:

./mb > out.log &

The > redirects output to a file so it doesn't show on the terminal, and
the & symbol sends it to the background on most POSIX shells.
-Brandon

**Comment by itrufeng** [comment]
cool. Thanks.
