### ISSUE TITLE
mountebank performance is horrible due to calling require inside http server hot paths

### ISSUE THREAD

**Issue by Havunen** [bbyars/mountebank#695]
We are running mountebank to mock external API endpoints and have been very happy with it so far.
However, recently we started doing load testing and noticed that our mountebank mock is not performing very well.
I ran profiler on mountebank and noticed that mountebank spends majority of its time in package resolution process.

Here is proof:
![image](https://user-images.githubusercontent.com/2021355/188567851-2eca2fbd-e263-43c5-bc22-19d347db22b0.png)
![image](https://user-images.githubusercontent.com/2021355/188567861-86decaed-2ec9-497b-8acb-fc1228ac64e9.png)

#### Expected behaviour

Javascript modules should not be loaded in hot paths

#### Actual behaviour

Mountebank is loading javascript modules in server connection, server request and so on...

#### Steps to reproduce

Create mountebank app and run any request to its endpoint

#### Software versions used

mountebank 2.7.0

**Comment by Havunen** [comment]
This is problem especially when running mountebank mock in cheap virtual container with low CPU / memory / I/O available

**Comment by Havunen** [comment]
Thank you for merging the PRs? Any estimation when new version is published to NPM?

**Comment by bbyars** [comment]
I've got some CircleCI failures related to another change on the npm
version. I'm troubleshooting now but will hopefully get it resolved this
week.

**Comment by pieterocp** [comment]
Looks to be fixed as per version 2.8.0, can probably close this issue.

**Comment by Havunen** [comment]
Closing this as the issue has been resolved.
