### ISSUE TITLE
Accepting Javascript object for 'body' field in request predicates

### ISSUE THREAD

**Issue by davcdhanesh1** [bbyars/mountebank#70]
I am currently using mountebank for asserting on the particular json object that should come in body payload. But as of my understanding it doesn't accept Javascript object for matching predicates in body field. Is there a specific reason for this ?

My imposter predicate looks like this.
```
"predicates": [
        {
          "and": [
            {
              "equals": {
                "path": "/test2",
                "method": "POST",
                "headers": {
                  "Content-Type": "application/json"
                }
              }
            },
            {
              "equals": {
                "body": { "name" : "dhanesh" }
              }
            }
          ]
        }
      ]
```

Even after using 'deepEquals' predicate instead of 'equals' it is still not able to match the predicate correctly.

**Comment by bbyars** [comment]
Hi Dhanesh,
Accepting JSON in the body is an interesting idea, but you're correct that
it's not currently supported, and I'm not sure it would work with all of
the predicates (e.g. matches, startsWith).  In your case, you probably want
a 'contains' predicate with a value of "{ \"name\": \"dhanesh\" }" or a
'matches' predicate if you want to be more tolerant of whitespace during
the serialization with a value of "{\s*\"name\"\s*:\s*\"dhanesh\"\s*}".
-Brandon

**Comment by bbyars** [comment]
suggest that this get moved to client libraries
