### ISSUE TITLE
Is that possible to delay the response?

### ISSUE THREAD

**Issue by moroshko** [bbyars/mountebank#71]
Hi, 

I wonder if that's possible to configure an imposter to return a response after a certain delay?

I'm trying to verify that a loading indicator appears on a screen while the request is in progress.

Thanks

**Comment by bbyars** [comment]
Hi Misha,
Absolutely!  Check out the wait behavior here
http://www.mbtest.org/docs/api/behaviors


On Monday, July 27, 2015, Misha Moroshko <notifications@github.com> wrote:

> Hi,
>
> I wonder if that's possible to configure an imposter to return a response
> after a certain delay?
>
> I'm trying to verify that a loading indicator appears on a screen while
> the request is in progress.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbyars/mountebank/issues/71>.
>


-- 
Sent from Gmail Mobile

**Comment by moroshko** [comment]
Great, thanks!!
