### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#77]
From Jeff Lage:
have you had any thoughts on how web sockets might fit in with mountebank?  for many of our web apps, though 90% of the API is HTTP, portions of it are delivered via web sockets and we'll need to mock those up also in test cycles.

**Comment by bbyars** [comment]
See https://groups.google.com/forum/#!topic/mountebank-discuss/t19u-sc8b6E

**Comment by bbyars** [comment]
This will have to be a new protocol implementation.  The RFC is here: https://tools.ietf.org/html/rfc6455

For the server, we can use socket.io or WebSocket-node (https://github.com/theturtle32/WebSocket-Node).  Based on 5 minutes of research, WebSocket-Node appears to be lower level and thus may be a better option - it takes in a single request object rather than abstracting that into event handlers for specific events on the server.

**Comment by phkavitha** [comment]
Is there any updates on this?

**Comment by bbyars** [comment]
Hi there,
Nothing yet; I have not started on it.
-Brandon

On Tuesday, March 22, 2016, Kavitha Haridas <notifications@github.com>
wrote:

> Is there any updates on this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bbyars/mountebank/issues/77#issuecomment-199900408>
>


-- 
Sent from Gmail Mobile

**Comment by bbyars** [comment]
See https://github.com/novnc/websockify

**Comment by bbyars** [comment]
Also the [Google group thread](https://groups.google.com/forum/#!searchin/mountebank-discuss/websocket$20support%7Csort:relevance/mountebank-discuss/t19u-sc8b6E/GoHUeC76DwAJ) shows how to use websockify to do it now

**Comment by jzabroski** [comment]
Seems to be essential in this day and age...

**Comment by bbyars** [comment]
Solved via community contribution and protocol extension
