### ISSUE TITLE
Provide pass through proxy

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#79]
See https://groups.google.com/forum/#!topic/mountebank-discuss/XK4PfD_ivXg

**Comment by bbyars** [comment]
From Sean Aitken:

````
Sure. The scenario is an existing set of API services (such as .NET WebApi), where we don't have good per-endpoint configuration options, or can't make configuration changes per endpoint. Let's just say there's over 50 pre-existing backend services that this API talks to.

We want to mock specific backend service calls while allowing everything else to just work. Over time, slowly build out a mock service repository to cover most backend services. This takes time.

By allowing mountebank to become an http proxy, it could allow all traffic to just flow through by default. Then, through predicates, select the traffic that should be mocked.

Then through configuration, or during deployment, a single change to use mountebank as the http(s) proxy for the web application, or from the client, should work. In the web.config file in .NET it's in one place (system.net/defaultProxy)... Covers all outbound backend calls that use standard stuff.

Also, acting as a proxy will allow the automatic resolution of target endpoint and path (since it's builtin to the http proxy protocol), meaning less configuration in MB.

Does that help?
````

Depending on how the forwarding information gets passed to the proxy, it could be some additional proxy config or a new `forwardProxy` response type.

**Comment by bbyars** [comment]
See https://groups.google.com/forum/#!topic/mountebank-discuss/o6WoFOf_gp8

**Comment by jrnelson333** [comment]
@bbyars - I am interested in using mountebanks to mock certain API requests, while letting a majority pass through. I wanted to confirm that until this is implemented that mountebank currently **does not** have the ability to act as a pass through proxy, meaning that each endpoint would need to be configured individually to proxy to the correct endpoints, and as new endpoints are added to an application that configuration changes would need to be made to have the new endpoints proxy to the correct endpoint.

Are there currently any know work arounds, or pass through proxies that can be used with mountebank for this use case?

Thanks,
Jordan

**Comment by bbyars** [comment]
Hi Jordan,
Sorry for the slow response; this one got lost in my inbox. 

The answer depends on what you mean by "endpoint." Right now, mountebank will support a default proxy, but it will be to a single destination (i.e. socket). If you put a stub with no predicates at the end of the stubs array, all requests that don't match anything above will be forwarded to that proxy. That destination can obviously support an infinite number of endpoints (i.e. paths).

What's missing, and will be until this issue is implemented, is the ability to forward on to any number of destinations (sockets) based on the URL. Right now, the workaround would be to code your own OS level proxy.
-Brandon

**Comment by bezda** [comment]
Wouldn't modifying https://github.com/bbyars/mountebank/blob/db46c4f83a3663af176088504fac4723383eeefd/src/models/responseResolver.js#L221 to 

```
return proxy.to(responseConfig.proxy.isTransparent ? request : responseConfig.proxy.to , request, responseConfig.proxy).then(function (response) {
```
do the job?

It wouldn't work for HTTPS, but it could be a simple solution for requested functionality

**Comment by bbyars** [comment]
Hi,
Yes, that looks close to me. The first parameter would likely need to be changed to match the `proxy.to` format (effectively the protocol + host).

**Comment by plee-nm** [comment]
@bbyars This proxy pass functionality would be different than supporting "paths" in the `to` url correct?  I am looking to do something like `to:http://localhost/a/b/c` and a request to `d` or `/d` would go to `http://localhost/a/b/c/d` instead of the current behavior of `http://localhost/a/b/c/d`.  Does that make sense?  Is my understanding of the current behavior correct?

**Comment by bbyars** [comment]
Solved with proxyTransparent
