### ISSUE TITLE
LDAP protocol support

### ISSUE THREAD

**Issue by bbyars** [bbyars/mountebank#85]

**Comment by PalSzak** [comment]
Is it in your roadmap?

**Comment by bbyars** [comment]
It's never been a priority, mainly due to lack of demand.  Can you tell me
a bit about what you're looking for?

**Comment by nottyo** [comment]
@bbyars I want this feature so much. There are some apps in my company that use the LDAP server as an user authentication server. Unfortunately, it's not stable sometimes, so I want to mock them to make sure that I can execute my tests at anytime. 

This is my rough idea for Mountebank to support for LDAP protocol.
Mountebank should accepts/decline bind request, allow user to set the predicates for search request and configure response message with simple format e.g. JSON.

I googled it and found the [ldapjs](http://ldapjs.org/) which provides API that can make a LDAP server.

**Comment by bbyars** [comment]
Thanks for the nudge; that's enough for me to move it out of the "wishlist" and into the roadmap. That said:
* I'd like to do https://github.com/bbyars/mountebank/issues/174 before implementing any new protocols
* I'm well over capacity at the moment, just keeping up with basic functionality and writing the book, so if you're depending on me it's several months out at least.

**Comment by dAnjou** [comment]
For anyone who still needs this, here is a really basic one: https://gitlab.com/dAnjou/mountebank-ldap

**Comment by bbyars** [comment]
Closed as community created through protocol extensions.
